### PR TITLE
Delete k8s cluster resource in e2e test

### LINKED ISSUE #576: e2e test fails if there are resouces created by the previous test
## Describe the feature:

The e2e test may fail in sometime, for example failing download docker image.  When start test again, it will fail for some existed resource. In this situation, I have to clear resource manually.
Is there a command or shell to clear all resource the test has created?

### PR DESCRIPTION
**Pull request by MIBc**
Fixes #576

## Proposed Changes

* Delete k8s cluster resource: `clusterrole`, `clusterrolebinding` after e2e test finish.

### CODE REVIEW

File: test/e2e/source_apiserver_test.go [hunk 1]
```diff
@@ -88,11 +91,28 @@ func (test *e2eTest) setupServiceAccountForApiserver(t *testing.T, name string)
...
+		t.Fatalf(fmt.Sprintf("Error executing 'kubectl create clusterrole testsa-role'. Error: %s", err.Error()))
 	}
 	_, err = kubectl.RunWithOpts([]string{"create", "clusterrolebinding", "testsa-binding", "--clusterrole=testsa-role", "--serviceaccount=" + test.kn.namespace + ":" + name}, runOpts{})
 	if err != nil {
-		t.Fatalf(fmt.Sprintf("Error executing 'kubectl clusterrolebinding testsa-binding'. Error: %s", err.Error()))
+		t.Fatalf(fmt.Sprintf("Error executing 'kubectl create clusterrolebinding testsa-binding'. Error: %s", err.Error()))
+	}
+}
+
+func (test *e2eTest) deleteServiceAccountForApiserver(t *testing.T, name string) {
```
Comment (navidshaikh) [inline test/e2e/source_apiserver_test.go]: This method is deleting ClusterRole and ClusterRoleBinding as well, IMO `tearDownForSourceApiServerTests` suites better for its name (similarly `setupServiceAccountForApiserver` in this file can be renamed to `setupForSourceApiServerTests`).

File: test/e2e/source_apiserver_test.go [hunk 2]
```diff
@@ -29,7 +29,10 @@ func TestSourceApiServer(t *testing.T) {
 	t.Parallel()
 	test := NewE2eTest(t)
 	test.Setup(t)
-	defer test.Teardown(t)
+	defer func() {
+		test.deleteServiceAccountForApiserver(t, "testsa")
```
Comment (navidshaikh) [inline test/e2e/source_apiserver_test.go]: Names for ServiceAccount, ClusterRole and ClusterRoleBindings can be set as constants and used uniformly for create/delete and references.

File: test/e2e/source_apiserver_test.go (hunk 1 above)
Comment (MIBc) [reply test/e2e/source_apiserver_test.go]: > I've added a few suggestions, can be addressed in a subsequent PR as well.

Yes, I will open a subsequent  pr.

Comment (navidshaikh) [reply test/e2e/source_apiserver_test.go]: #597
