### PR TITLE
Uses BYO revision names for traffic splitting e2e tests

### LINKED ISSUE #500: e2e test failed
Affected PRs: #495 #484, which needs retest after fixing this.
Logs from e2e test:
```
=== RUN   TestTrafficSplit/replace_latest_tag_of_a_revision_with_old_and_give_latest_to_another_revision
Running 'kn service create echo12 --image gcr.io/knative-samples/helloworld-go -n kne2etests2'...
Running 'kn service describe echo12 -o jsonpath={.status.latestCreatedRevisionName} -n kne2etests2'...
Running 'kn service update echo12 --env TARGET=v2 -n kne2etests2'...
Running 'kn service describe echo12 -o jsonpath={.status.latestCreatedRevisionName} -n kne2etests2'...
Running 'kn service update echo12 --tag echo12-cpjww-1=latest -n kne2etests2'...
Running 'kn service update echo12 --untag latest --tag echo12-cpjww-1=old,echo12-mstfw-2=latest -n kne2etests2'...
Running 'kn service describe echo12 -o jsonpath={range .status.traffic[*]}{.tag}{','}{.revisionName}{','}{.percent}{','}{.latestRevision}{'|'}{end} -n kne2etests2'...
Running 'kn service delete echo12 -n kne2etests2'...
Running 'kubectl delete namespace kne2etests2'...
--- FAIL: TestTrafficSplit (338.92s)
    --- PASS: TestTrafficSplit/tag_two_revisions_as_v1_and_v2_and_give_50-50%_share (39.34s)
    --- PASS: TestTrafficSplit/ramp/up_down_a_revision_to_20%_adjusting_other_traffic_to_accommodate (14.25s)
    --- FAIL: TestTrafficSplit/tag_a_revision_as_candidate,_without_otherwise_changing_any_traffic_split (7.74s)
        traffic_split_test.go:368: assertion failed: 
            --- expectedTargets
            +++ formattedActualTargets
              []e2e.TargetFields{
              	{
              		Tag:      "",
            - 		Revision: "echo2-ytdyn-2",
            + 		Revision: "echo2-qjxkx-1",
              		Percent:  100,
              		Latest:   true,
              	},
              	{Tag: "candidate", Revision: "echo2-qjxkx-1"},
              }
            
    --- FAIL: TestTrafficSplit/tag_a_revision_as_candidate,_set_2%_traffic_adjusting_other_traffic_to_accommodate (7.12s)
        traffic_split_test.go:368: assertion failed: 
            --- expectedTargets
            +++ formattedActualTargets
              []e2e.TargetFields{
              	{
              		Tag:      "",
            - 		Revision: "echo3-rxqpk-2",
            + 		Revision: "echo3-yvncn-1",
              		Percent:  98,
              		Latest:   true,
              	},
              	{Tag: "candidate", Revision: "echo3-yvncn-1", Percent: 2},
              }
            
    --- PASS: TestTrafficSplit/update_tag_for_a_revision_from_candidate_to_current,_tag_current_is_present_on_another_revision (16.57s)
    --- PASS: TestTrafficSplit/update_tag_from_testing_to_staging_for_@latest_revision (8.58s)
    --- PASS: TestTrafficSplit/update_tag_from_testing_to_staging_for_a_revision_(non_@latest) (9.47s)
    --- PASS: TestTrafficSplit/remove_a_revision_with_tag_old_from_traffic_block_entirely (10.26s)
    --- PASS: TestTrafficSplit/tag_a_revision_as_stable_and_current_with_50-50%_traffic (7.37s)
    --- FAIL: TestTrafficSplit/revert_all_traffic_to_latest_ready_revision_of_service (6.42s)
        traffic_split_test.go:368: assertion failed: 
            --- expectedTargets
            +++ formattedActualTargets
              []e2e.TargetFields{
              	{
              		Tag:      "",
            - 		Revision: "echo9-jjnkt-2",
            + 		Revision: "echo9-wymdj-1",
              		Percent:  100,
              		Latest:   true,
              	},
              }
            
    --- PASS: TestTrafficSplit/tag_latest_ready_revision_of_service_as_current (6.66s)
    --- PASS: TestTrafficSplit/update_tag_for_a_revision_as_testing_and_assign_all_the_traffic_to_it: (10.60s)
    --- PASS: TestTrafficSplit/replace_latest_tag_of_a_revision_with_old_and_give_latest_to_another_revision (9.97s)
FAIL
FAIL	knative.dev/client/test/e2e	338.954s
Finished run, return code is 1
XML report written to /logs/artifacts/junit_BCtKZlsF.xml
```

### PR DESCRIPTION
**Pull request by navidshaikh**
Fixes #500 

## Proposed Changes
* Uses BYO revision names for traffic splitting e2e tests
* Avoid getting the revision name after service create/update using LCR or LRR from service status
* Pauses 3 seconds before verifying actual vs expected traffic targets ( Check the comment on https://github.com/knative/client/issues/500#issuecomment-554355688)

/lint

### CODE REVIEW

File: test/e2e/traffic_split_test.go [hunk 1]
```diff
@@ -368,9 +376,9 @@ func (test *e2eTest) verifyTargets(t *testing.T, serviceName string, expectedTar
 	assert.DeepEqual(t, expectedTargets, formattedActualTargets)
 }
 
-func (test *e2eTest) latestRevisionOfService(t *testing.T, serviceName string) string {
-	return test.serviceDescribeWithJsonPath(t, serviceName, latestRevisionJsonPath)
-}
+//func (test *e2eTest) latestReadyRevisionOfService(t *testing.T, serviceName string) string {
+//	return test.serviceDescribeWithJsonPath(t, serviceName, LRRJsonPath)
+//}
```
Comment (navidshaikh) [inline test/e2e/traffic_split_test.go]: removing the commented function

Comment (navidshaikh) [reply test/e2e/traffic_split_test.go]: ok, will take it off in different PR.
