### PR TITLE
List inbuilt sources if CRD access is restricted

### LINKED ISSUE #947: kn source list and list-types return error if CRD access is restricted
### Bug report
`kn source list` and `kn source list-types` uses dynamic client and a common operation is to query CRDs and filter on a particular label. It finds all the sources CRDs with label `duck.knative.dev/source: true`, and able to list eventing inbuilt and non inbuilt sources.
A user of cluster might be restricted to list the CRDs in the cluster causing `kn source list` and `kn source list-types` commands to fail, though the same user is able to read the particular GVK of the source (kn source ping list).
We can identify these restricted access error and fallback to listing only eventing inbuilt sources as we know their GVKs.

### PR DESCRIPTION
**Pull request by navidshaikh**
## Description
- Identify restricted access error
- If server returns restricted access error, fallback to listing
  only eventing inbuilt sources using their GVKs.
- List every typed source and read the error
  to know if eventing is installed for `kn source list-types`.

## Changes
-  Add `isForbiddenError` in kn error factory
-  Add `ListSourcesUsingGVKs` to dynamic client
-  Add  `BuiltInSourcesGVKs` to `pkg/sources/v1alpha2/client.go` which returns inbuilt source GVKs

## Reference
Fixes #947 

/lint

### CODE REVIEW

File: pkg/errors/factory.go [hunk 1]
```diff
@@ -38,6 +39,10 @@ func isEmptyConfigError(err error) bool {
 	return strings.Contains(err.Error(), "no configuration has been provided")
 }
 
+func IsForbiddenError(status api_errors.APIStatus) bool {
```
[the remark this answers is not in the document]
Comment (navidshaikh) [reply pkg/errors/factory.go]: changed to unexported method

**Comment by navidshaikh** [comment]
@rhuss @maximilien @daisy-ycguo: I will add the tests if the approach looks good.

File: pkg/kn/commands/source/list.go [hunk 2]
```diff
@@ -58,8 +61,15 @@ func NewListCommand(p *commands.KnParams) *cobra.Command {
 			}
 			sourceList, err := dynamicClient.ListSources(filters...)
 			if err != nil {
-				return err
+				if strings.HasPrefix(knerrors.GetError(err).Error(), "403") {
```
[the remark this answers is not in the document]
Comment (navidshaikh) [reply pkg/kn/commands/source/list.go:64]: We are processing the error at https://github.com/knative/client/pull/948/files#diff-1a1baf9d1fe0b4fa3d8d4e515233df48R42 where we're prefixing api status code (403 in case of forbidden) to message.
Though we can change harcoded `403` here and fetch that from lib.

File: pkg/dynamic/client.go [hunk 3]
```diff
@@ -141,14 +146,56 @@ func (c *knDynamicClient) ListSources(types ...WithType) (*unstructured.Unstruct
...
-			numberOfsourceTypesFound++
+			numberOfSourceTypesFound++
+			sourceList.Items = append(sourceList.Items, sList.Items...)
+			sourceList.SetGroupVersionKind(sList.GetObjectKind().GroupVersionKind())
+		}
+	}
+	// Clear the Group and Version for list if there are multiple types of source objects found
+	// Keep the source's GVK if there is only one type of source objects found or requested via --type filter
+	if numberOfSourceTypesFound > 1 {
+		sourceList.SetGroupVersionKind(schema.GroupVersionKind{Group: "", Version: "", Kind: "List"})
```
[the remark this answers is not in the document]
Comment (navidshaikh) [reply pkg/dynamic/client.go:157]: This was done to show proper values if json or yaml format of list is requested and the list contains multiple types of source objects.

[the remark this answers is not in the document]
Comment (navidshaikh) [reply pkg/dynamic/client.go:157]: We'd need GVK set for the (list) object here as (json/yaml) printers require it. The question was which version/group to set if there are different types of sources found, so we set cleared group and version values and set `List` for kind. 
If there is only one type of source object found OR user requested single type using `--type` filter, we keep the GVK intact.

File: pkg/dynamic/client.go [hunk 4]
```diff
@@ -107,12 +113,17 @@ func (c *knDynamicClient) ListSources(types ...WithType) (*unstructured.Unstruct
...
 		options                  metav1.ListOptions
-		numberOfsourceTypesFound int
+		numberOfSourceTypesFound int
 	)
 	sourceTypes, err := c.ListSourcesTypes()
 	if err != nil {
 		return nil, err
 	}
+
+	if sourceTypes == nil || len(sourceTypes.Items) == 0 {
```
Comment (maximilien) [inline pkg/dynamic/client.go:123]: I can comment this condition (both parts around ||) and still pass all tests...

File: pkg/kn/commands/source/list.go [hunk 5]
```diff
@@ -52,15 +54,25 @@ func NewListCommand(p *commands.KnParams) *cobra.Command {
...
-			if err != nil {
-				return err
+
+			switch {
+			case knerrors.IsForbiddenError(err):
+				gvks := sourcesv1alpha2.BuiltInSourcesGVKs()
+				if sourceList, err = dynamicClient.ListSourcesUsingGVKs(&gvks, filters...); err != nil {
+					return knerrors.GetError(err)
+				}
+			case err != nil:
```
Comment (maximilien) [inline pkg/kn/commands/source/list.go:71]: I can comment lines 71-73 and still pass all tests...

File: pkg/kn/commands/source/list_types.go [hunk 6]
```diff
@@ -47,13 +52,17 @@ func NewListTypesCommand(p *commands.KnParams) *cobra.Command {
 			}
 
 			sourceListTypes, err := dynamicClient.ListSourcesTypes()
-			if err != nil {
-				return err
+			switch {
+			case knerrors.IsForbiddenError(err):
```
Comment (maximilien) [inline pkg/kn/commands/source/list_types.go:56]: I can comment lines 56-59 and still pass all tests

File: pkg/kn/commands/source/list_types.go [hunk 7]
```diff
@@ -47,13 +52,17 @@ func NewListTypesCommand(p *commands.KnParams) *cobra.Command {
...
+					return knerrors.GetError(err)
+				}
+			case err != nil:
+				return knerrors.GetError(err)
 			}
 
-			if len(sourceListTypes.Items) == 0 {
-				fmt.Fprintf(cmd.OutOrStdout(), "No sources found.\n")
-				return nil
+			if sourceListTypes == nil || len(sourceListTypes.Items) == 0 {
```
Comment (maximilien) [inline pkg/kn/commands/source/list_types.go:64]: I can comment either parts around the || and still have all tests green...

File: pkg/dynamic/client.go (hunk 3 above)
[the remark this answers is not in the document]
Comment (rhuss) [reply pkg/dynamic/client.go:163]: Yes, but imagine the situation that by accident you have only one source of one type. If you list those, you the GVK set. Some time later another source of another type is added. Suddenly know the GVK gets removed or changed to an artificial "List". I think as we are dealing with a heterogenous list, that, by accident, can be also homogenous, we should treat it as a heterogenous list always. I would not mind to introduce a new type here, like we did for the `Export`, with an `client.knative.dev` group and a `v1alpha1` version for now, but then use it all the time.

File: pkg/kn/commands/source/list_types.go (hunk 6 above)
Comment (navidshaikh) [reply pkg/kn/commands/source/list_types.go:56]: added https://github.com/knative/client/issues/952 to track adding mock client for dynamic client, with which we should be able to pass the errors to expect and verify this in unit tests, can be added in a separate PR, sounds good?

File: pkg/kn/commands/source/list.go (hunk 5 above)
Comment (navidshaikh) [reply pkg/kn/commands/source/list.go:71]: added tests

File: pkg/dynamic/client.go (hunk 4 above)
Comment (navidshaikh) [reply pkg/dynamic/client.go:123]: added tests

File: pkg/kn/commands/source/list_types.go (hunk 7 above)
Comment (navidshaikh) [reply pkg/kn/commands/source/list_types.go:64]: added tests

File: pkg/dynamic/client.go (hunk 3 above)
[the remark this answers is not in the document]
Comment (navidshaikh) [reply pkg/dynamic/client.go:163]: > I would not mind to introduce a new type here, like we did for the Export, with an client.knative.dev group and a v1alpha1 version for now, but then use it all the time.

yea, we could do that, however for the other point about list of single source type, I think setting exact source type for single-type-of-source list is explicit and we could scope the client custom type for list *only* if there multiple types of sources.

[the remark this answers is not in the document]
Comment (navidshaikh) [reply pkg/dynamic/client.go:163]: Added https://github.com/knative/client/issues/953 to track adding setting this custom client type for list. We can refine in next iteration.

File: pkg/dynamic/client.go [hunk 8]
```diff
@@ -141,14 +152,56 @@ func (c *knDynamicClient) ListSources(types ...WithType) (*unstructured.Unstruct
...
+
+	var (
+		sourceList               unstructured.UnstructuredList
+		options                  metav1.ListOptions
+		numberOfSourceTypesFound int
+	)
+	namespace := c.Namespace()
+	filters := WithTypes(types).List()
+
+	for _, gvk := range *gvks {
```
Comment (daisy-ycguo) [inline pkg/dynamic/client.go:182]: Just wonder what's the better behavior when `gvks` is `nil`: a) return a `nil` list or b) ignore `gvks` and use `types ...WithType` to filter.
I see when `types` is nil, the behavior is to b) ignore `types` and use `gvks` to filter, not a) return a `nil` list. Maybe we use the same logic to handle either of these two parameters is nil.

File: pkg/kn/commands/source/list_test.go [hunk 9]
```diff
@@ -71,6 +79,20 @@ func TestSourceListTypesNoHeaders(t *testing.T) {
 	assert.Check(t, util.ContainsAll(output[0], "PingSource"))
 }
 
+func TestListBuiltInSources(t *testing.T) {
```
Comment (daisy-ycguo) [inline pkg/kn/commands/source/list_test.go:82]: I will suggest to use `TestListBuiltInSourceTypes` other than `TestListBuiltInSources` because the method is to test listing of builtin source types, other than sources.

File: pkg/dynamic/client.go [hunk 10]
```diff
@@ -141,14 +152,56 @@ func (c *knDynamicClient) ListSources(types ...WithType) (*unstructured.Unstruct
...
+	// Clear the Group and Version for list if there are multiple types of source objects found
+	// Keep the source's GVK if there is only one type of source objects found or requested via --type filter
+	if numberOfSourceTypesFound > 1 {
+		sourceList.SetGroupVersionKind(schema.GroupVersionKind{Group: "", Version: "", Kind: "List"})
+	}
+	return &sourceList, nil
+}
+
+// ListSourcesUsingGVKs returns list of available source objects using given list of GVKs
+func (c *knDynamicClient) ListSourcesUsingGVKs(gvks *[]schema.GroupVersionKind, types ...WithType) (*unstructured.UnstructuredList, error) {
```
Comment (daisy-ycguo) [inline pkg/dynamic/client.go:169]: I wonder what is the best function behavior when `gvks` is `nil`: a) to return a `nil` list or b) to ignore `gvks` and use `types` to filter. The current behavior is a).
Yet when `types` is `nil`, the current behavior is b) to ignore `types` and use `gvks` to filter, not a) to return a `nil` list. It makes me a little weird. 
Of course it doesn't affect the current functions. For future usage, maybe change to the same behavior when either of these two parameters is `nil`.

Comment (navidshaikh) [reply pkg/dynamic/client.go:169]: We use `types` only to subset the found source types. If gvks list is nil, it returns nil. Does this answer your question ?

File: pkg/kn/commands/source/list_test.go (hunk 9 above)
Comment (navidshaikh) [reply pkg/kn/commands/source/list_test.go]: updated

**Comment by navidshaikh** [comment]
/retest

    24.839s Ingress has not yet been reconciled.
    Error: timeout: service 'hello' not ready after 600 seconds

**Comment by navidshaikh** [comment]
/retest

    27.413s Ingress has not yet been reconciled.
