### PR TITLE
Fix --image flag to only allow single occurence

### LINKED ISSUE #533: Does not reject multiple `--image` parameters
## What version of Knative Client?

> Paste output of 'kn version'

```
$ kn version
Version:      v0.10.0
Build Date:   2019-11-07 15:02:21
Git Revision: 22c65d6
Supported APIs:
- serving.knative.dev/v1alpha1 (knative-serving v0.10.0)
```

## What version of Knative Serving running on your cluster?

0.10

## Expected Behavior

When I type `kn update service --image example.com/first --image example.com/second`, I expect to be told that I cannot provide two images.

## Actual Behavior

`kn` accepts the command line without error or warning. It applies the last-provided argument. In the example above this means that the updated service has `example.com/second` as its image.

## Steps to Reproduce the Problem

1. Create a service.
1. Update the service, using two different `--image` parameters.
1. Observe that no error occurs.
1. Use describe to observe that second parameter is applied.

### PR DESCRIPTION
**Pull request by dsimansk**
Fixes #533 

## Proposed Changes

* Introduce new type `singletonString` for flag values that only allow single value assignment, otherwise return error
* Fix `--image` flag with the new type.

Example:
```bash
➜  client git:(issue-533) kn service create svc-test --image gcr.io/knative-samples/helloworld-go --image gcr.io/foo/bar:barz --no-wait 
invalid argument "gcr.io/foo/bar:barz" for "--image" flag: value is already set
```

### CODE REVIEW

File: pkg/kn/commands/service/configuration_edit_flags.go [hunk 1]
```diff
@@ -67,6 +67,25 @@ type ResourceFlags struct {
...
 }
 
+// -- singletonString Value
+// Custom implementation of flag.Value interface to prevent multiple value assignment.
+// Useful to enforce single use of flag, e.g. --image.
+type singletonString string
+
+func (s *singletonString) Set(val string) error {
+	if len(*s) > 0 {
+		return errors.New("value is already set")
```
Comment (rhuss) [inline pkg/kn/commands/service/configuration_edit_flags.go]: I'm not sure how this "feels" like on the CLI. If this is the only error printed, then it might be confusing (especially when you have a large list of options). It would be better to actually print *which* argument was duplicated (i.e. `--image` here). I think you could implement that by using a type like

```golang
type uniqueStringArg struct {  
   // which kind of argument it is
    kind string 

   // Argument value
   value string
}

func newUniqueStringArg(kind string) uniqueStringArg {
     return uniqueStringArg{kind: kind}
}
```

and then partially pre-initialize the ConfiguarionEditFlags like in 

```golang
ceF = ConfigurationEditFlags{
    Image: newUniqueStringArg("image")
}
```

and then finally adapt the error message to include the `kind`. 

Does this make sense ?

Comment (dsimansk) [reply pkg/kn/commands/service/configuration_edit_flags.go]: Actually, the error already contains the flag.
```
```

Comment (dsimansk) [reply pkg/kn/commands/service/configuration_edit_flags.go]: Maybe a bit more descriptive error message?

Comment (rhuss) [reply pkg/kn/commands/service/configuration_edit_flags.go]: Ah, if this is the case, then I'm fine with having the current solution.

However for the error message I woudl use something like "flag can be provided only once" (so from the POV of the user, not from the flag's POV)

Comment (dsimansk) [reply pkg/kn/commands/service/configuration_edit_flags.go]: OK, anyway I do like your suggested name `uniqueStringArg` a bit more. I'll change the name, error message and finally add some unit tests.

Comment (dsimansk) [reply pkg/kn/commands/service/configuration_edit_flags.go]: Reflected review feedback in https://github.com/knative/client/pull/647/commits/c68fe1dbf790fab2b341d56de8f543ad9c80378d and added unit tests in https://github.com/knative/client/pull/647/commits/c9902886ceed29d5fe57068f603dedb8500636d2.

File: pkg/kn/commands/service/create_test.go [hunk 2]
```diff
@@ -134,6 +134,12 @@ func TestServiceCreateImage(t *testing.T) {
 	}
 }
 
+func TestServiceCreateWithMultipleImages(t *testing.T) {
+	_, _, _, err := fakeServiceCreate([]string{
+		"service", "create", "foo", "--image", "gcr.io/foo/bar:baz", "--image", "gcr.io/bar/foo:baz", "--no-wait"}, false, false)
+	assert.Error(t, err, "invalid argument \"gcr.io/bar/foo:baz\" for \"--image\" flag: can be provided only once")
```
Comment (rhuss) [inline pkg/kn/commands/service/create_test.go]: What we also do typically in unit test to assert on the content of the error message: not the exact wording but that key context information is included. This helps us to ensure that the error message is meaningful, but the test is also as robust as possible so that the exact wording could be changed without breaking the tests.

We have an utility `util.ContainsAll()` which helps here. Check for other tests that use that method.

File: pkg/kn/commands/service/configuration_edit_flags.go [hunk 3]
```diff
@@ -67,6 +67,25 @@ type ResourceFlags struct {
 	Memory string
 }
 
+// -- uniqueStringArg Value
+// Custom implementation of flag.Value interface to prevent multiple value assignment.
```
Comment (maximilien) [inline pkg/kn/commands/service/configuration_edit_flags.go]: Clever :)
