### PR TITLE
fix(769): various issues with godoc documents

### LINKED ISSUE #769: test: fix typos/docstrings
from https://github.com/knative/client/pull/765 review

### PR DESCRIPTION
**Pull request by maximilien**
## Description

Fixes various godoc comments that are not conforming as well as some /lint issues that came up

## Changes

* correct signatures for some functions with with non-conforming names
* various corrections to Godoc comments for exported code in new lib/test
* fix CHANGELOG.doc for new location for common test code

## Reference

Fixes #769

/lint

### CODE REVIEW

File: lib/test/cli.go [hunk 1]
```diff
@@ -33,7 +33,7 @@ type Kn struct {
 	namespace string
 }
 
-// New Kn object
+// NewKn object
```
Comment (navidshaikh) [inline lib/test/cli.go:36]:
```suggestion
// NewKn creates a new Kn object
```

File: lib/test/integration.go [hunk 2]
```diff
@@ -68,7 +68,7 @@ func (test *KnTest) Teardown() error {
 	return DeleteNamespace(test.namespace)
 }
 
-// Teardown clean up
+// Kn object used by this KnTest
```
Comment (navidshaikh) [inline lib/test/integration.go:71]:
```suggestion
// Kn returns object used by this KnTest
```

File: test/e2e/service_options_test.go [hunk 3]
```diff
@@ -107,9 +107,9 @@ func TestServiceOptions(t *testing.T) {
 		assert.NilError(t, err)
 	}
 	serviceCreateWithOptions(t, it, r, "svc6", "--user", strconv.FormatInt(uid, 10))
-	validateUserId(t, it, r, "svc6", uid)
+	validateUserID(t, it, r, "svc6", uid)
 	serviceUpdate(t, it, r, "svc6", "--user", strconv.FormatInt(uid+1, 10))
-	validateUserId(t, it, r, "svc6", uid+1)
+	validateUserID(t, it, r, "svc6", uid+1)
 }
```
Comment (navidshaikh) [inline test/e2e/service_options_test.go:113]: :+1:

File: test/e2e/source_apiserver_test.go [hunk 4]
```diff
@@ -50,7 +50,7 @@ func TestSourceApiServer(t *testing.T) {
 	r := test.NewKnRunResultCollector(t)
 	defer r.DumpIfFailed()
 
-	setupForSourceApiServer(t, it)
+	setupForSourceAPIServer(t, it)
```
Comment (navidshaikh) [inline test/e2e/source_apiserver_test.go:53]: :+1:
