### PR TITLE
Return Error Message from Using --untag with Nonexistent Tag

### LINKED ISSUE #874: traffic tags: Error if requested for removing non-existing tag
### Bug report
If requested to untag a non-existing tag in traffic block, add an error.

### Expected behavior
`service update` command returns error message indicating the tag doesnt exists for service and non-zero exit status.

### Steps to reproduce the problem
1. `kn service create hello --image knativesamples/helloworld`
2. `kn service update hello --untag foo --no-wait`

### kn version
latest

### Knative (serving/eventing) version
v0.15.0

### PR DESCRIPTION
**Pull request by danielhelfand**
## Description

This pull request returns an error message when using `kn service update serviceName --untag tagName --no-wait` on a tag that does not exist.

The error returned by `kn` will be as follows, but I am open to any change with regard to the message:

```
Error: tag tagName does not exist
```

In the event multiple nonexistent tags are specified, `kn` will return multiple errors:

```
kn service update serviceName --untag tagName --untag tagName2 --no-wait

Error: tag tagName does not exist
Error: tag tagName2 does not exist
```

If a tag that does exist is specified with a nonexistent tag, the error will be displayed and no update will be made. 

Please let me know if this should warrant an e2e test as well.

## Reference

Fixes #874

/lint

### CODE REVIEW

File: pkg/kn/commands/service/update_test.go [hunk 1]
```diff
@@ -737,6 +737,15 @@ func TestServiceUpdateDeletionTimestampNotNil(t *testing.T) {
 	assert.ErrorContains(t, err, "service")
 }
 
+func TestServiceUpdateTagDoesNotExist(t *testing.T) {
+	orig := newEmptyService()
+
+	_, _, _, err := fakeServiceUpdate(orig, []string{
+		"service", "update", "foo", "--untag", "foo", "--no-wait"})
+
+	assert.Error(t, err, "Error: tag foo does not exist")
```
Comment (rhuss) [inline pkg/kn/commands/service/update_test.go:746]: I'd suggest to change this to (please add the import, too, if missing0:

```go
assert.Assert(t, util.ContainsAll(err.Error(), "tag", "foo", "not exist"))
```

It's always very fragile to assert on the exact wording of something, which might slight improvements tedious to work on (as then always a test needs to be fixed). Instead, just check that the important _context information_ is contained in the error message. This focus also having good error message which as much context information as possible to help a user to understand and fix the error. E.g. Here you could also add the service name which would help the user to understand which service you wanted to tag. The more context, the better.

Also, please use error message according to the golang standard: Starting lower case, no punctuation at the need. The "Error:" prefix is also redundant here (its an error anyway), and in fact the top-level routine which prints the error will add the error prefix anyway. So better remove it here, too.

We have an issues open (not sure where), where we want to check for all error messages to be consistently following this rule. Might be a good exercise to automate that and make it part of the build process.

File: pkg/kn/traffic/compute.go [hunk 2]
```diff
@@ -276,8 +278,17 @@ func Compute(cmd *cobra.Command, targets []servingv1.TrafficTarget, trafficFlags
...
-		traffic.untagRevision(tag)
+		err = traffic.untagRevision(tag)
+		if err != nil {
+			errStrings = append(errStrings, err.Error())
+		}
+	}
+
+	// Return all errors from untagging revisions
+	if len(errStrings) > 0 {
+		return nil, fmt.Errorf(strings.Join(errStrings, "\n"))
```
Comment (rhuss) [inline pkg/kn/traffic/compute.go:291]: Please don't add any formatting like `\n` to the end of an error message. Use a `", "` instead as separator.

File: pkg/kn/traffic/compute_test.go [hunk 3]
```diff
@@ -278,6 +278,18 @@ func TestComputeErrMsg(t *testing.T) {
 			[]string{"--traffic", "echo-v1=40", "--traffic", "echo-v1=60"},
 			"repetition of revision reference echo-v1 is not allowed, use only once with --traffic flag",
 		},
+		{
+			"untag single tag that does not exist",
+			append(newServiceTraffic([]servingv1.TrafficTarget{}), newTarget("latest", "echo-v1", 100, false)),
+			[]string{"--untag", "foo"},
+			"Error: tag foo does not exist",
```
Comment (rhuss) [inline pkg/kn/traffic/compute_test.go:285]: See my first comment: I would never check on the exact wording of an error message as this might change (e.g. like for the suggestions I made, e.g. to avoid the `Error` prefix and add the service information.

File: pkg/kn/commands/service/update.go [hunk 4]
```diff
@@ -92,7 +92,7 @@ func NewServiceUpdateCommand(p *commands.KnParams) *cobra.Command {
 				}
 
 				if trafficFlags.Changed(cmd) {
-					traffic, err := traffic.Compute(cmd, service.Spec.Traffic, &trafficFlags)
+					traffic, err := traffic.Compute(cmd, service.Spec.Traffic, &trafficFlags, service.Name)
```
Comment (danielhelfand) [inline pkg/kn/commands/service/update.go:95]: Added `serviceName` parameter to `traffic.Compute` to pass service name for error messaging. Let me know if there is another option for getting the service name in `compute.go` that would get rid of the need to pass data from here.

File: pkg/kn/traffic/compute.go [hunk 5]
```diff
@@ -276,8 +279,17 @@ func Compute(cmd *cobra.Command, targets []servingv1.TrafficTarget, trafficFlags
...
-		traffic.untagRevision(tag)
+		tagName := traffic.untagRevision(tag, serviceName)
+		if tagName != "" {
+			errTagNames = append(errTagNames, tagName)
+		}
+	}
+
+	// Return all errors from untagging revisions
+	if len(errTagNames) > 0 {
+		return nil, fmt.Errorf("tag(s) %s not present for any revisions of service %s", strings.Join(errTagNames, ", "), serviceName)
```
Comment (danielhelfand) [inline pkg/kn/traffic/compute.go:292]: Updated formatting of error message to include all invalid tags used with `--untag` for a particular service and including name for more context with the error message.

File: pkg/kn/traffic/compute_test.go (hunk 3 above)
Comment (danielhelfand) [reply pkg/kn/traffic/compute_test.go]: Due to the structure of the tests, can we leave this in place for now? They seem to focus on the exact error message via `assert.Error(t, err, testCase.errMsg)`. However, would be happy to adapt the tests here maybe as a separate issue/pr.

File: pkg/kn/traffic/compute.go (hunk 2 above)
Comment (danielhelfand) [reply pkg/kn/traffic/compute.go]: Believe this is addressed by comment below:

https://github.com/knative/client/pull/880#discussion_r437513614

File: pkg/kn/commands/service/update_test.go (hunk 1 above)
Comment (danielhelfand) [reply pkg/kn/commands/service/update_test.go]: Just to clarify here, the `error: ` prefix won't be added unless included in the message it seems:

```
./kn service update hello --untag foo --no-wait

tag(s) foo not present for any revisions of service hello
```

File: pkg/kn/traffic/compute_test.go (hunk 3 above)
Comment (rhuss) [reply pkg/kn/traffic/compute_test.go]: I'm fine with that.

File: pkg/kn/commands/service/update_test.go (hunk 1 above)
Comment (rhuss) [reply pkg/kn/commands/service/update_test.go]: Totally agree, that a consistent error handling is missing, but for consistency's sake, I think there should be a single point which prepares an error message for print out.

In fact, in the refactoring in #877 there is a single exit point in case of a custom error, that now adds the appropriate prefix --> https://github.com/knative/client/blob/a71cc3fd91b9722e983929709c84ee9fd29939c5/cmd/kn/main.go#L38-L41

We can more error messaging mangling at this point (like uppercasing the first letter), but if we assume that the change above gets merged, then we should already avoid an `Error:` prefix.

Comment (rhuss) [reply pkg/kn/commands/service/update_test.go]: But don't let that block this PR as we have to go over all error messages later anyway.

File: pkg/kn/traffic/compute.go [hunk 6]
```diff
@@ -276,8 +279,17 @@ func Compute(cmd *cobra.Command, targets []servingv1.TrafficTarget, trafficFlags
 	traffic := newServiceTraffic(targets)
 
 	// First precedence: Untag revisions
+	var errTagNames []string
 	for _, tag := range trafficFlags.UntagRevisions {
-		traffic.untagRevision(tag)
+		tagName := traffic.untagRevision(tag, serviceName)
+		if tagName != "" {
+			errTagNames = append(errTagNames, tagName)
+		}
```
Comment (navidshaikh) [inline pkg/kn/traffic/compute.go:287]: We're returning the value from function which is passed as its own arguments, 
I think `untagRevsion` could return a bool value based on status of the operation?
