### PR TITLE
Skip non modified event first while waiting for ready

### LINKED ISSUE #1389: WaitForReady should check for event type before trying to read generation number
### Bug report

The code at location supplied behaves badly in a situation when it receives an event of type different from _MODIFIED_, in which the underlying object doesn't contain a status field yet.

That situation is completely normal, as _ADDED_ event can be received first, and the resource at that point may not possess a _status_ field yet.

https://github.com/knative/client/blob/e26d5f27cab3c554963ea0f69507f89d766cd9b0/pkg/wait/wait_for_ready.go#L183-L207

Such situation I've observed while developing wait on ready based on dynamic client at https://github.com/knative-sandbox/kn-plugin-event/pull/38

The actual error that is being returned is similar to:

```
cannot extract status from &{map[metadata:map[creationTimestamp:<nil> generation:1 name:test-service] spec:map[template:map[metadata:map[creationTimestamp:<nil>] spec:map[containers:<nil>]]]]}
```

### Expected behavior

When _WaitForReady_ receives an event of type different from MODIFIED, it should skip it first, before checking anything in the underlying object structure.

### Steps to reproduce the problem

https://github.com/cardil/knative-client/commit/7ca076911e098b1a68ab742f1a11bb1492c1d7c8

### Knative (serving/eventing) version

> Nightly
> 0.24

### PR DESCRIPTION
**Pull request by cardil**
## Description

Allow using wait for ready with dynamic kube client, as before this change, an error was received on _Added_ event with unstructured object, which by default doesn't have `.status` field.

## Changes

* 🐛 Bug fix of #1389 - Skipping on non-modified event while waiting for ready

## Reference

Fixes #1389

### CODE REVIEW

File: pkg/wait/wait_for_ready_test.go [hunk 1]
```diff
@@ -325,6 +322,25 @@ func peNormal(name string) ([]watch.Event, int) {
 	}, len(messages)
 }
 
+func peUnstructured(name string) ([]watch.Event, int) {
+	events, msgLen := peNormal(name)
+	for i, event := range events {
+		unC, err := runtime.DefaultUnstructuredConverter.ToUnstructured(event.Object)
+		if err != nil {
+			panic(err)
```
Comment (maximilien) [inline pkg/wait/wait_for_ready_test.go:330]: Why not just fail test here with a message?

**Review by maximilien — COMMENTED** [review]
/ok-to-test

**Comment by itsmurugappan** [comment]
lgtm, but to pass the code cov test, the lines that were changed need to have more than 76.51 % coverage.

File: pkg/wait/wait_for_ready_test.go (hunk 1 above)
Comment (cardil) [reply pkg/wait/wait_for_ready_test.go:330]: Yes, I could. But, that requires passing down the `testing.T`. Panic in test isn't nice, because if it fires tests in that package will stop and not be reported properly.

I thought maybe it's not worth it, as this mapping to unstructured data should always pass. And to pass `testing.T` it would require additional code changes.

**Comment by dsimansk** [comment]
> lgtm, but to pass the code cov test, the lines that were changed need to have more than 76.51 % coverage.

@cardil can you please take a look at the coverage? We've discussed on WG call that if it's too cumbersome to reach some of the statements it can be even merged without reaching the required number, just let us know please. :)

**Comment by cardil** [comment]
@itsmurugappan @dsimansk I did raise the coverage on reported method, although it's a synthetic example that shouldn't occur with duck elements, which always should have generation and observed generation. Now, this PR passes all the gates.

**Review by itsmurugappan — APPROVED** [review]
/lgtm

**Comment by itsmurugappan** [comment]
cool, coverage also jumping by 1.68%  👍

**Comment by dsimansk** [comment]
Since it's addressing all the review comments, imo it's good to go.
/approve

**Comment by cardil** [comment]
This PR needs _approve_ label also.
