### PR TITLE
fixes(#308): adds e2e tests for plugins

### LINKED ISSUE #308: Kn plugins integration test
## In what area(s)?

Kn plugins

Classifications:

/kind feature

## Describe the feature:

Now that #249 is merged we need to have a separate integration test (IT) for that feature. There is a lot to test. As a start, let's add this:

1. simple plugin execution of a BASH and executable plugin in
  a. `--plugins-dir`
  b.  $PATH
2. finding plugin in both `--plugins-dir` and $PATH
3. verifying plugin overshadowing
4. verifying plugin cannot override a core command

---
There will be more to add to these ITs as plugins matures and more features are added.

### PR DESCRIPTION
**Pull request by maximilien**
Fixes #308

## Proposed Changes

* adds `test/e2e/plugins_test.go`
* adds a new option to `e2eTest` to prevent namespace creation (since some test might not need ns)

Release Note:

- 🧽 backfill e2e tests for plugins

### CODE REVIEW

File: test/e2e/plugins_test.go [hunk 1]
```diff
@@ -0,0 +1,210 @@
...
+		t.Run("when using --plugin-dir", func(t *testing.T) {
+			t.Run("when --plugins-dir has a plugin", func(t *testing.T) {
+				t.Run("when --lookup-plugins is false", func(t *testing.T) {
+					lookupPlugins = false
+
+					setup(t)
+					defer teardown(t)
+
+					knFlags := []string{fmt.Sprintf("--plugins-dir=%s", knPluginsDir), "--lookup-plugins=false"}
+					assert.Assert(t, lookupPlugins == false)
```
Comment (navidshaikh) [inline test/e2e/plugins_test.go]:
```suggestion

```

`lookupPlugins` not being operated after its set.

File: test/e2e/plugins_test.go [hunk 2]
```diff
@@ -0,0 +1,210 @@
...
+	err := ioutil.WriteFile(pluginFilename, []byte(pluginCode), FileModeExecutable)
+	if err != nil {
+		return "", err
+	}
+	return pluginFilename, nil
+}
+
+func (test *e2eTest) listPlugin(t *testing.T, knFlags []string, expectedPlugins []string, unexpectedPlugins []string) {
+	knArgs := addArgs([]string{}, knFlags...)
+	knArgs = addArgs(knArgs, []string{"plugin", "list"}...)
```
Comment (navidshaikh) [inline test/e2e/plugins_test.go]:
```suggestion
	knArgs := append(knFlags, []string{"plugin", "list"}...)
```

File: test/e2e/plugins_test.go [hunk 3]
```diff
@@ -0,0 +1,210 @@
...
+		assert.Check(t, util.ContainsAll(out, output))
+	}
+}
+
+func addArgs(cmdArgs []string, args ...string) []string {
+	for _, arg := range args {
+		cmdArgs = append(cmdArgs, arg)
+	}
+	return cmdArgs
+}
```
Comment (navidshaikh) [inline test/e2e/plugins_test.go]: Remove.

File: test/e2e/plugins_test.go [hunk 4]
```diff
@@ -0,0 +1,210 @@
...
+	knArgs := addArgs([]string{}, knFlags...)
+	knArgs = addArgs(knArgs, []string{"plugin", "list"}...)
+
+	out, err := test.kn.RunWithOpts(knArgs, runOpts{NoNamespace: true})
+	assert.Assert(t, err == nil)
+	assert.Check(t, util.ContainsAll(out, expectedPlugins...))
+	assert.Check(t, util.ContainsNone(out, unexpectedPlugins...))
+}
+
+func (test *e2eTest) runPlugin(t *testing.T, knFlags []string, pluginName string, args []string, expectedOutput []string) {
```
Comment (navidshaikh) [inline test/e2e/plugins_test.go]: `expectedOutput` can just be string here?

File: test/e2e/plugins_test.go [hunk 5]
```diff
@@ -0,0 +1,210 @@
...
+	"gotest.tools/assert"
+	"knative.dev/client/pkg/util"
+)
+
+const (
+	TestPluginCode string = `#!/bin/bash
+
+echo "Hello Knative, I'm a Kn plugin"
+echo "  My plugin file is $0"
+echo "  I recieved arguments: $1 $2 $3 $4"`
```
Comment (navidshaikh) [inline test/e2e/plugins_test.go]: *received

File: test/e2e/plugins_test.go [hunk 6]
```diff
@@ -0,0 +1,210 @@
...
+				})
+
+				t.Run("with --lookup-plugins is true", func(t *testing.T) {
+					lookupPlugins = true
+
+					setup(t)
+					defer teardown(t)
+
+					knFlags := []string{fmt.Sprintf("--plugins-dir=%s", knPluginsDir), "--lookup-plugins=true"}
+					assert.Assert(t, lookupPlugins == true)
```
Comment (navidshaikh) [inline test/e2e/plugins_test.go]:
```suggestion

```

unnecessary check

File: test/e2e/plugins_test.go [hunk 7]
```diff
@@ -0,0 +1,210 @@
...
+					})
+				})
+			})
+		})
+	})
+}
+
+// Private
+
+func (test *e2eTest) createConfig(t *testing.T, configName, configCode, configPath string) (string, error) {
```
Comment (navidshaikh) [inline test/e2e/plugins_test.go]:
```suggestion
func (test *e2eTest) createConfig(t *testing.T, configFilename, configData, configDir string) (string, error) {
```
(symbol renames)

actually should be ordered as Dir, Filename, Data


```suggestion
func (test *e2eTest) createConfig(t *testing.T, configDir, configFilename, configData string) (string, error) {
```

File: test/e2e/plugins_test.go [hunk 8]
```diff
@@ -0,0 +1,210 @@
...
+
+	t.Parallel()
+	test := NewE2eTest(t)
+	setup := func(t *testing.T) {
+		test.createNamespaceOnSetup = false
+		test.Setup(t)
+		defer test.Teardown(t)
+
+		knConfigDir, err = ioutil.TempDir("", "kn-config")
+		assert.Assert(t, err == nil)
```
Comment (navidshaikh) [inline test/e2e/plugins_test.go]:
```suggestion
		assert.NilError(t, err)
```

Comment (navidshaikh) [reply test/e2e/plugins_test.go]: also for other similar checks

File: test/e2e/plugins_test.go [hunk 9]
```diff
@@ -0,0 +1,210 @@
...
+}
+
+// Private
+
+func (test *e2eTest) createConfig(t *testing.T, configName, configCode, configPath string) (string, error) {
+	configFilename := filepath.Join(configPath, configName)
+	err := ioutil.WriteFile(configFilename, []byte(configCode), FileModeReadWrite)
+	if err != nil {
+		return "", err
+	}
```
Comment (navidshaikh) [inline test/e2e/plugins_test.go]:
```
	assert.NilError(t, err)
```

File: test/e2e/plugins_test.go [hunk 10]
```diff
@@ -0,0 +1,210 @@
...
+}
+
+func (test *e2eTest) createPlugin(t *testing.T, pluginName, pluginCode, pluginPath string) (string, error) {
+	pluginFilename := filepath.Join(pluginPath, pluginName)
+	err := ioutil.WriteFile(pluginFilename, []byte(pluginCode), FileModeExecutable)
+	if err != nil {
+		return "", err
+	}
+	return pluginFilename, nil
+}
```
Comment (navidshaikh) [inline test/e2e/plugins_test.go]: Actually, `createConfig` and `createPlugin` should be merged into `createFile` taking `Dir, Filename, data, FilePermission` args.

File: test/e2e/plugins_test.go [hunk 11]
```diff
@@ -0,0 +1,210 @@
...
+		assert.Assert(t, knConfigPath != "")
+
+		knPluginPath, err = test.createPlugin(t, "kn-helloe2e", TestPluginCode, knPluginsDir)
+		assert.Assert(t, err == nil)
+		assert.Assert(t, knPluginPath != "")
+
+		knPluginPath2, err = test.createPlugin(t, "kn-hello2e2e", TestPluginCode, knPluginsDir2)
+		assert.Assert(t, err == nil)
+		assert.Assert(t, knPluginPath2 != "")
+	}
```
Comment (navidshaikh) [inline test/e2e/plugins_test.go]: IMO, we should take off this code from setup and move to individual test runs. We should then also be able to test cases  like, if the plugin name overrides the built in commands/verbs.

File: test/e2e/common.go [hunk 12]
```diff
@@ -47,22 +47,27 @@ const (
...
 
 // Setup set up an environment for kn integration test returns the Teardown cleanup function
 func (test *e2eTest) Setup(t *testing.T) {
 	test.env.Namespace = fmt.Sprintf("%s%d", test.env.Namespace, getNamespaceCountAndIncrement())
 	test.kn = kn{t, test.env.Namespace, Logger{}}
-	test.CreateTestNamespace(t, test.env.Namespace)
-	time.Sleep(20 * time.Second)
+	if test.createNamespaceOnSetup {
+		test.CreateTestNamespace(t, test.env.Namespace)
+		time.Sleep(20 * time.Second)
```
Comment (navidshaikh) [inline test/e2e/common.go]: why `time.Sleep`?

File: test/e2e/plugins_test.go (hunk 2 above)
Comment (maximilien) [reply test/e2e/plugins_test.go]: OK. Good suggestion. Thanks.

File: test/e2e/plugins_test.go (hunk 4 above)
Comment (maximilien) [reply test/e2e/plugins_test.go]: 👍

File: test/e2e/plugins_test.go (hunk 3 above)
Comment (maximilien) [reply test/e2e/plugins_test.go]: 👍

File: test/e2e/plugins_test.go (hunk 5 above)
Comment (maximilien) [reply test/e2e/plugins_test.go]: Thx

File: test/e2e/plugins_test.go (hunk 8 above)
Comment (maximilien) [reply test/e2e/plugins_test.go]: OK

File: test/e2e/common.go (hunk 12 above)
Comment (maximilien) [reply test/e2e/common.go]: We always had that sleep since namespaces take time to create. See previous code.

We can experiment with smaller values but that's a separate PR.

I had to make namespace creation optional since this plugin e2e would have created a namespace but never used it.

File: test/e2e/plugins_test.go (hunk 9 above)
Comment (maximilien) [reply test/e2e/plugins_test.go]: OK

File: test/e2e/plugins_test.go (hunk 6 above)
Comment (maximilien) [reply test/e2e/plugins_test.go]: Well because the `lookupPlugins` is a variable, the `setup(t)` could have changed it and since this block is about `lookupPlugins` either `true` or `false` wanted to ensure that.

File: test/e2e/plugins_test.go (hunk 4 above)
Comment (maximilien) [reply test/e2e/plugins_test.go]: Want to check for multiple lines

File: test/e2e/plugins_test.go (hunk 11 above)
Comment (maximilien) [reply test/e2e/plugins_test.go]: I already have tests for "plugin name overrides the built in commands/verbs." in the `pkg/commands/plugin` package and you won't see the overrides until the plugin is ran.

File: test/e2e/common.go (hunk 12 above)
Comment (maximilien) [reply test/e2e/common.go]: Was in previous code so kept it. I think was there to give time for namespace to be created.

I think we should probably reduce the time since NS creation might be faster. However, that's a separate PR.

I'll open an issue to try to get e2e tests faster and point to that line as one place.

Comment (maximilien) [reply test/e2e/common.go]: I created issue #598

**Comment by maximilien** [comment]
@navidshaikh I need to work on this a bit more. Will submit updates sometimes tomorrow.

File: test/e2e/plugins_test.go (hunk 10 above)
Comment (maximilien) [reply test/e2e/plugins_test.go]: OK. Good point. Done.

**Comment by maximilien** [comment]
> @navidshaikh I need to work on this a bit more. Will submit updates sometimes tomorrow.

Actually, got a bit of breather with other things and completed it before leaving for home. See update. Thanks.

**Comment by maximilien** [comment]
@navidshaikh I am not sure why the IT tests failed. Let me try it again.

File: test/e2e/plugins_test.go (hunk 9 above)
Comment (navidshaikh) [reply test/e2e/plugins_test.go]: The `err` here is already asserted for NilError, `if err != nil` check is not needed. 
Also err is being checked here, so `createFile` method doesn't need to return the `err` in this case.

Comment (maximilien) [reply test/e2e/plugins_test.go]: OK fair. Pushed new updates to address. Thx.
