### PR TITLE
fix(plugin): Fix plugin lookup with file ext on Windows

### LINKED ISSUE #767: Plugins can't be executed without extension on Windows
### Bug report

kn 0.13.1 on Windows is not able to execute plugin without specifying the extension:
```
PS C:\Users\hudson> kn version
Version:      v0.13.1
Build Date:   2020-03-26 15:54:06
Git Revision: ff2a302
Supported APIs:
* Serving
  - serving.knative.dev/v1 (knative-serving v0.13.0)
* Eventing
  - sources.eventing.knative.dev/v1alpha1 (knative-eventing v0.13.1)
  - sources.eventing.knative.dev/v1alpha2 (knative-eventing v0.13.1)
  - eventing.knative.dev/v1alpha1 (knative-eventing v0.13.1)
PS C:\Users\hudson> kn plugin list
C:\Users\hudson.DESKTOP-T61GB27\AppData\Roaming\kn\plugins\kn-hello.bat
PS C:\Users\hudson> kn hello
Error: unknown command 'hello'
Run 'kn --help' for usage.
PS C:\Users\hudson> kn hello.bat
Hello Knative, I'm a Kn plugin
  My plugin file is C:\Users\hudson.DESKTOP-T61GB27\AppData\Roaming\kn\plugins\kn-hello.bat
  I received arguments: C:\Users\hudson.DESKTOP-T61GB27\AppData\Roaming\kn\plugins\kn-hello.bat
```
### Expected behavior

`kn hello` executes `kn-hello.bat` plugin
### Steps to reproduce the problem

1. create `kn-hello.bat` file in `~\AppData\Roaming\kn\plugins\`
```
@echo off
echo Hello Knative, I'm a Kn plugin
echo   My plugin file is %0
echo   I received arguments: %1 %2 %3 %4
```
2. run `kn hello`

### kn version

```
PS C:\Users\hudson> kn version
Version:      v0.13.1
Build Date:   2020-03-26 15:54:06
Git Revision: ff2a302
Supported APIs:
* Serving
  - serving.knative.dev/v1 (knative-serving v0.13.0)
* Eventing
  - sources.eventing.knative.dev/v1alpha1 (knative-eventing v0.13.1)
  - sources.eventing.knative.dev/v1alpha2 (knative-eventing v0.13.1)
  - eventing.knative.dev/v1alpha1 (knative-eventing v0.13.1)
```

### PR DESCRIPTION
**Pull request by dsimansk**
## Changes

* Change plugin lookup to try to match well-know file extensions

## Reference

Fixes #767

### CODE REVIEW

File: pkg/kn/commands/plugin/handler.go [hunk 1]
```diff
@@ -76,6 +76,16 @@ func (h *DefaultPluginHandler) Lookup(name string) (string, bool) {
 			return pluginDirPluginPath, true
 		}
 
+		// Try to match well-known file extensions on Windows
+		if runtime.GOOS == "windows" {
+			for _, ext := range []string{".bat", ".cmd", ".com", ".exe", ".ps1"} {
+				pathWithExt := pluginDirPluginPath + ext
+				if _, err = os.Stat(pathWithExt); !os.IsNotExist(err) {
```
Comment (rhuss) [inline pkg/kn/commands/plugin/handler.go:83]: What if `err != nil` but also `!os.IsNotExist()` is true ? (i.e. if there is an error as than not-found). The path is then returned nevertheless, which imo is wrong. (same error btw in the check above, too).

IMO this method should return `(string,err)` with an empy string if nothing is found, non-empty string if the plugin is found and err if any other error occured.

Comment (maximilien) [reply pkg/kn/commands/plugin/handler.go:83]: Also just split the `os.Stat` and `os.IsNotExit` to make logic clear

Comment (dsimansk) [reply pkg/kn/commands/plugin/handler.go]: For now I've opted for less invasive solution that will only check `err == nil` to fix the reported issue. And also allow straightforward cherry-pick to  `release-0.13`. 

I agree that we should look closer to handler code and improve Lookup as suggested by @rhuss and anything else that will come up.

File: pkg/kn/commands/plugin/handler.go [hunk 2]
```diff
@@ -76,6 +76,17 @@ func (h *DefaultPluginHandler) Lookup(name string) (string, bool) {
 			return pluginDirPluginPath, true
 		}
 
+		// Try to match well-known file extensions on Windows
```
Comment (rhuss) [inline pkg/kn/commands/plugin/handler.go:79]: @dsimansk while we are at it, could you please also adapt the three lines above (just to be consistent) and add a comment that we should strive for a more sophisticated error handling in the future ?

Comment (dsimansk) [reply pkg/kn/commands/plugin/handler.go:79]: Sure, will do.
