### PR TITLE
fixes(#586): simplifies service update message to user

### LINKED ISSUE #586: service update final message is confusing (could be improved)
## In what area(s)?

`kn service update`

Classifications:

> /kind cleanup

## What version of Knative Client?

```bash
➜  client git:(master) ✗ ./kn version
Using kn config file: /Users/maximilien/.kn/config.yaml
Version:      v20191220-local-d03cbf9-dirty
Build Date:   2019-12-20 21:27:38
Git Revision: d03cbf9
Supported APIs:
* Serving
  - serving.knative.dev/v1alpha1 (knative-serving v0.11.0)
* Eventing
  - sources.eventing.knative.dev/v1alpha1 (knative-eventing v0.11.0)
  - eventing.knative.dev/v1alpha1 (knative-eventing v0.11.0)
```
## What version of Knative Serving running on your cluster?

> 0.11.0

## Expected Behavior

When updating services I expect a message that is clear about what changes is shown to the user.

## Actual Behavior

```bash
➜  client git:(master) ./kn service describe summary-fn
Using kn config file: /Users/maximilien/.kn/config.yaml
Name:       summary-fn
Namespace:  default
Labels:     knfun=demo
Age:        39d
URL:        http://summary-fn-default.kndemo-267179.sjc03.containers.appdomain.cloud

Revisions:
   50%  summary-fn-hwkll-31 (current @latest) #async [20] (23d)
        Image:  index.docker.io/drmax/summary-fn@sha256:415f521bac57ae8bac8fd51b09f53a38ef879935283ee1649d40842689db3e2b (at 415f52)
   50%  summary-fn-qwfdb-1 #sync [19] (23d)
        Image:  docker.io/drmax/summary-fn:latest (pinned to 415f52)

Conditions:
  OK TYPE                   AGE REASON
  ++ Ready                   5s
  ++ ConfigurationsReady    23d
  ++ RoutesReady             5s

➜  client git:(master) ./kn service update summary-fn --tag summary-fn-qwfdb-1=sync
Using kn config file: /Users/maximilien/.kn/config.yaml
Updating Service 'summary-fn' in namespace 'default':

  0.090s Ready to serve.

Service 'summary-fn' updated with latest revision 'summary-fn-hwkll-31' (unchanged) and URL:
http://summary-fn-default.kndemo-267179.sjc03.containers.appdomain.cloud
```
The word `updated` in the last message is confusing and conflicts with `unchanged` which I understand applies to the revision but could be made clearer.

## Steps to Reproduce the Problem

above

### PR DESCRIPTION
**Pull request by maximilien**
Fixes #586

## Proposed Changes

* splits final service update to user to make clear what changed and what has not

```bash
➜  client git:(master) ✗ ./kn service update summary-fn --untag sync1
Using kn config file: /Users/maximilien/.kn/config.yaml
Updating Service 'summary-fn' in namespace 'default':

  0.089s Ready to serve.

Service 'summary-fn' with latest revision 'summary-fn-nxqwb-41' (unchanged) is available at URL:
http://summary-fn-default.kndemo-267179.sjc03.containers.appdomain.cloud
```

This is a case when service is updated with tags and revision remained unchanged.

```bash
➜  client git:(master) ✗ ./kn service update summary-fn --image docker.io/drmax/summary-fn:latest
Using kn config file: /Users/maximilien/.kn/config.yaml
Updating Service 'summary-fn' in namespace 'default':

  0.091s The Configuration is still working to reflect the latest desired specification.
  6.317s Ready to serve.

Service 'summary-fn' updated to latest revision 'summary-fn-jfjcy-42' is available at URL:
http://summary-fn-default.kndemo-267179.sjc03.containers.appdomain.cloud
```

This is the case when service updated to new revision.

Release Note:

- 🧽 clarifies service update message

### CODE REVIEW

**Comment by maximilien** [comment]
@navidshaikh @rhuss can I get a quick review on this. Thanks

File: pkg/kn/commands/service/service.go [hunk 1]
```diff
@@ -66,8 +66,13 @@ func showUrl(client serving_kn_v1alpha1.KnServingClient, serviceName string, ori
 	revisionUpdateStatus := ""
 	newRevision := service.Status.LatestReadyRevisionName
 	if originalRevision != "" && originalRevision == newRevision {
-		revisionUpdateStatus = " (unchanged)"
+		revisionUpdateStatus = "unchanged"
```
Comment (rhuss) [inline pkg/kn/commands/service/service.go]: Instead of introducing this temporary variable to check later on, I suggest to directly print the two different messages directly in the two branches of this if statement and remove the second if.

Comment (maximilien) [reply pkg/kn/commands/service/service.go]: OK that's fair. See update. Pushing now. Thanks.
