### PR TITLE
Run plugin on Windows

### LINKED ISSUE #737: Plugins can't be executed on Windows
### Bug report

We use `syscall.Exec()` as underlying mechanism to execute plugins locally. However, `syscall` doesn't support Windows as [target platform](https://github.com/golang/go/issues/30662).

The very same problem resolved in [kubectl](https://github.com/kubernetes/kubernetes/pull/76227).

https://github.com/knative/client/blob/db569fae177eb41d688399c33f2d9de64875568f/pkg/kn/commands/plugin/handler.go#L94-L97

### Expected behavior

`kn` plugins are executable on Windows.

### kn version
HEAD

/kind good-first-issue

### PR DESCRIPTION
**Pull request by MIBc**
Fixes #737

* Use exec.Command instend of syscall.Exec for windows.
* Fix a bug in plugin handler test when running it on windows.
* Fix typo.

Release Note:
- 🐛 Bug fix
 Using exec.Command instend of syscall.Exec for windows.

### CODE REVIEW

File: pkg/kn/commands/plugin/handler_test.go [hunk 1]
```diff
@@ -134,6 +138,14 @@ func TestPluginHandler(t *testing.T) {
 			err = pluginHandler.Execute(bogusPath, []string{bogusPath}, os.Environ())
 			assert.Assert(t, err != nil, fmt.Sprintf("bogus plugin in path %s unexpectedly executed OK", bogusPath))
 		})
+		t.Run("executing fake plugin successfully", func(t *testing.T) {
+			setup(t)
+			defer cleanup(t)
+			beforeEach(t)
+
```
Comment (mattmoor) [inline pkg/kn/commands/plugin/handler_test.go]: Remove trailing whitespace:
```suggestion

```

File: pkg/kn/commands/plugin/handler.go [hunk 2]
```diff
@@ -22,8 +22,8 @@ import (
 	"path/filepath"
```
Comment (mattmoor) [inline pkg/kn/commands/plugin/handler.go]: Format Go code:
```suggestion
	"path/filepath"
	"runtime"
```

File: pkg/kn/commands/plugin/handler.go [hunk 3]
```diff
@@ -22,8 +22,8 @@ import (
...
 	"strings"
 	"syscall"
```
Comment (mattmoor) [inline pkg/kn/commands/plugin/handler.go]: Format Go code:
```suggestion
	"syscall"

```

File: pkg/kn/commands/plugin/handler.go [hunk 4]
```diff
@@ -22,8 +22,8 @@ import (
...
-
-	homedir "github.com/mitchellh/go-homedir"
+	"github.com/mitchellh/go-homedir"
+	"runtime"
```
Comment (mattmoor) [inline pkg/kn/commands/plugin/handler.go]: Format Go code:
```suggestion

```

File: pkg/kn/commands/plugin/handler_test.go (hunk 1 above)
Comment (mattmoor) [inline pkg/kn/commands/plugin/handler_test.go]: Format Go code:
```suggestion

```

**Comment by rhuss** [comment]
> Produced via:
> `gofmt -s -w $(find -path './vendor' -prune -o -path './third_party' -prune -o -type f -name '*.go' -print)`

@mattmoor Could we please switch off this check ? A mentioned [elsewhere](https://github.com/knative/client/pull/629#issuecomment-597258517) we are using `goimports` as part of our regular build. Goimports has a slightly different opinion of how imports are organized (no idea why), but having this suggestions are too noisy imo causing unnecessary friction. Also, the next build will rearrange it again.

Just out of curiosity: Why did you stop using a dedicated bot account and use your real account for both activities (manual and automated PR/reviews) ? Asking, because quite some stats (like in TOC meetings or also when it comes for the TOC election process) are based on contributions, not sure whether automated commits (like these) are diluting these stats.

**Comment by rhuss** [comment]
@MIBc please don't apply the reformatting suggestions, you will see if you rerun `build.sh` the imports will get rearranged again.

File: pkg/kn/commands/plugin/handler.go [hunk 5]
```diff
@@ -93,6 +94,14 @@ func (h *DefaultPluginHandler) Lookup(name string) (string, bool) {
 
 // Execute implements PluginHandler
 func (h *DefaultPluginHandler) Execute(executablePath string, cmdArgs, environment []string) error {
+	if runtime.GOOS == "windows" {
+		cmd := exec.Command(executablePath, cmdArgs...)
+		cmd.Stdout = os.Stdout
```
Comment (maximilien) [inline pkg/kn/commands/plugin/handler.go]: Could we do the same pattern for all runtime?

Comment (MIBc) [reply pkg/kn/commands/plugin/handler.go]: I have read https://github.com/golang/go/issues/30662#issuecomment-470701281 and https://github.com/kubernetes/kubernetes/pull/76227/files#r284055366. 
The `exec` performs different  behaviors. On windows it fork a new process to run plugin . On Unix systems it starts a new executable in the same process.
Therefore I think it is hard to make the same pattern for all runtime. It may bring some unknown risks.

Comment (maximilien) [reply pkg/kn/commands/plugin/handler.go]: Thanks. Still would love for someone to test this on Windows independently. Otherwise we’ll have to take your word for it. My guess is most everyone in WG are non-Windows users.

Comment (MIBc) [reply pkg/kn/commands/plugin/handler.go]: Yes. We need test on different platforms. I have test it both on windows and linux.

**Comment by dsimansk** [comment]
@MIBc @maximilien 
I have access to Windows on my home PC. So I've tried to check the current PR, but I'm still seeing a weird error message. Even though that plugin is executed, there's also and `unknown command ` displayed afterwards.

Have you seen such behavior during your tests?

```
C:\Users\StyX\Desktop>kn-windows-amd64.exe hello.bat --plugins-dir=C:\Users\StyX\AppData\Roaming\kn\plugins
"Hello!"
unknown command "hello.bat" for "kn"
```

`kn-hello.bat`
```bat
@ECHO OFF
ECHO "Hello!"  
```

**Comment by MIBc** [comment]
> @MIBc @maximilien
> I have access to Windows on my home PC. So I've tried to check the current PR, but I'm still seeing a weird error message. Even though that plugin is executed, there's also and `unknown command ` displayed afterwards.
> 
> Have you seen such behavior during your tests? Otherwise the PR looks good.
> 
> ```
> C:\Users\StyX\Desktop>kn-windows-amd64.exe hello.bat --plugins-dir=C:\Users\StyX\AppData\Roaming\kn\plugins
> "Hello!"
> unknown command "hello.bat" for "kn"
> ```
> 
> `kn-hello.bat`
> 
> ```batchfile
> @ECHO OFF
> ECHO "Hello!"  
> ```

Plugin's name should begin with `kn`. Like `kn-hello.bat`

**Comment by dsimansk** [comment]
@MIBc I had to add the following lines that're also part of `kubectl` [implementation](https://github.com/kubernetes/kubernetes/pull/76227/files#diff-f23cc6c004fbd8a713f8465465142ab8R376).

Per conversation with @navidshaikh. He found out that this behaviour is reproducible on Linux as well, if `exec.Command` is used instead of `syscall.Exec`.

```
➜  client git:(pr-738) ✗ git --no-pager diff
diff --git a/pkg/kn/commands/plugin/handler.go b/pkg/kn/commands/plugin/handler.go
index 1d05169..7ee7c4e 100644
--- a/pkg/kn/commands/plugin/handler.go
+++ b/pkg/kn/commands/plugin/handler.go
@@ -100,7 +100,11 @@ func (h *DefaultPluginHandler) Execute(executablePath string, cmdArgs, environme
 		cmd.Stderr = os.Stderr
 		cmd.Stdin = os.Stdin
 		cmd.Env = environment
-		return cmd.Run()
+		err := cmd.Run()
+		if err == nil {
+			os.Exit(0)
+		}
+		return err
 	}
 	return syscall.Exec(executablePath, cmdArgs, environment)
 }
```

**Comment by MIBc** [comment]
Yes. It needs an exit code when using exec.Command on windows .

**Comment by dsimansk** [comment]
Thanks!
/lgtm

File: pkg/kn/commands/plugin/handler.go (hunk 5 above)
Comment (maximilien) [reply pkg/kn/commands/plugin/handler.go]: Nice thanks @MIBc will LGTM

File: CHANGELOG.adoc [hunk 6]
```diff
@@ -22,6 +22,10 @@
 | Fix trigger create --filter flag to be optional
 | https://github.com/knative/client/pull/735[#745]
 
+| 🐛
+| Using exec.Command instend of syscall.Exec for windows.
```
[the remark this answers is not in the document]
Comment (navidshaikh) [reply CHANGELOG.adoc]: or
```
Fix plugin execution for Windows
```

**Comment by rhuss** [comment]
When this PR is merged, can we cherry pick the commit also to `release-0.13` branch so that it gets part of `0.13.1` ?

**Comment by navidshaikh** [comment]
+1 for getting this for 0.13.1

@MIBc : could you quickly fix the typo in CHANGELOG ?
or we can merge the PR and fix in cherry pick PR too.

File: CHANGELOG.adoc (hunk 6 above)
[the remark this answers is not in the document]
Comment (MIBc) [reply CHANGELOG.adoc]: done
