### PR TITLE
fix(e2e): Use build.sh for compiling

### LINKED ISSUE #174: build flag -mod=vendor only valid when using modules -- failed to test the integration tests with e2e-test.sh
I created a google project called vincent-knative as the project to launch the kube cluster. I got error when running the integration tests.
Does anyone know how to configure the env to run the integration tests for knative client?
The error message is "build flag -mod=vendor only valid when using modules" for running "go build -v -mod=vendor ./cmd/...".
What kind of environment variables do I need to set? Thx.

The error I got by running ./e2e-test.sh:

<details>
<summary>command output</summary>

```
VincentMacBookPro:test vincent$ export PROJECT_ID=vincent-knative
VincentMacBookPro:test vincent$ ./e2e-tests.sh 
$PROJECT_ID is set to 'vincent-knative', using it to run the tests
=========================
==== BUILDING CLIENT ====
=========================
build flag -mod=vendor only valid when using modules
ERROR: cluster setup failed
***************************************
***         E2E TEST FAILED         ***
***    Start of information dump    ***
***************************************
>>> All resources:
NAMESPACE      NAME                                                            READY   STATUS      RESTARTS   AGE
istio-system   pod/istio-citadel-5c88f4f47d-tghsm                              1/1     Running     0          26m
istio-system   pod/istio-cleanup-secrets-1.1.3-qxnpr                           0/1     Completed   0          26m
istio-system   pod/istio-galley-6c78cdcfc4-g2b5w                               1/1     Running     0          26m
istio-system   pod/istio-ingressgateway-7f6db9967c-v6dqs                       1/1     Running     0          26m
istio-system   pod/istio-init-crd-10-7mkmj                                     0/1     Completed   0          26m
istio-system   pod/istio-init-crd-11-gwkd5                                     0/1     Completed   0          26m
istio-system   pod/istio-pilot-56df8c9cf6-2m94q                                2/2     Running     0          26m
istio-system   pod/istio-policy-68775985b8-67gmw                               2/2     Running     3          26m
istio-system   pod/istio-security-post-install-1.1.3-whz95                     0/1     Completed   0          26m
istio-system   pod/istio-sidecar-injector-bc79fc549-qmckw                      1/1     Running     0          26m
istio-system   pod/istio-telemetry-5965f9d996-687c8                            2/2     Running     3          26m
istio-system   pod/promsd-f876c8c55-n92lc                                      2/2     Running     1          26m
kube-system    pod/event-exporter-v0.2.5-7d99d74cf8-n5rg4                      2/2     Running     0          26m
kube-system    pod/fluentd-gcp-scaler-55bdf597c-2xhbz                          1/1     Running     0          26m
kube-system    pod/fluentd-gcp-v3.1.1-4b84l                                    2/2     Running     0          25m
kube-system    pod/fluentd-gcp-v3.1.1-t44rj                                    2/2     Running     0          25m
kube-system    pod/fluentd-gcp-v3.1.1-z7znh                                    2/2     Running     0          25m
kube-system    pod/heapster-v1.6.1-75c89cf597-xwcr4                            3/3     Running     0          26m
kube-system    pod/kube-dns-6987857fdb-gpvkc                                   4/4     Running     0          26m
kube-system    pod/kube-dns-6987857fdb-xn4df                                   4/4     Running     0          26m
kube-system    pod/kube-dns-autoscaler-bb58c6784-mp2dm                         1/1     Running     0          26m
kube-system    pod/kube-proxy-gke-knative-default-pool-0b861d45-bb9t           1/1     Running     0          26m
kube-system    pod/kube-proxy-gke-knative-default-pool-0b861d45-bs83           1/1     Running     0          26m
kube-system    pod/kube-proxy-gke-knative-default-pool-0b861d45-pvmn           1/1     Running     0          26m
kube-system    pod/l7-default-backend-fd59995cd-4cqw6                          1/1     Running     0          26m
kube-system    pod/metrics-server-v0.3.1-57c75779f-z2sp7                       2/2     Running     0          26m
kube-system    pod/prometheus-to-sd-b65l2                                      1/1     Running     0          26m
kube-system    pod/prometheus-to-sd-qnpsm                                      1/1     Running     0          26m
kube-system    pod/prometheus-to-sd-z9sxg                                      1/1     Running     0          26m
kube-system    pod/stackdriver-metadata-agent-cluster-level-7b549bd965-8w4vp   1/1     Running     4          26m

NAMESPACE      NAME                             TYPE           CLUSTER-IP     EXTERNAL-IP     PORT(S)                                                                                                                                      AGE
default        service/kubernetes               ClusterIP      10.20.0.1      <none>          443/TCP                                                                                                                                      28m
istio-system   service/istio-citadel            ClusterIP      10.20.7.36     <none>          8060/TCP,15014/TCP                                                                                                                           25m
istio-system   service/istio-galley             ClusterIP      10.20.3.49     <none>          443/TCP,15014/TCP,9901/TCP                                                                                                                   25m
istio-system   service/istio-ingressgateway     LoadBalancer   10.20.12.139   34.83.198.217   15020:32744/TCP,80:31380/TCP,443:31390/TCP,31400:31400/TCP,15029:31099/TCP,15030:30804/TCP,15031:30428/TCP,15032:30766/TCP,15443:32692/TCP   25m
istio-system   service/istio-pilot              ClusterIP      10.20.12.244   <none>          15010/TCP,15011/TCP,8080/TCP,15014/TCP                                                                                                       25m
istio-system   service/istio-policy             ClusterIP      10.20.7.186    <none>          9091/TCP,15004/TCP,15014/TCP                                                                                                                 25m
istio-system   service/istio-sidecar-injector   ClusterIP      10.20.10.224   <none>          443/TCP                                                                                                                                      25m
istio-system   service/istio-telemetry          ClusterIP      10.20.14.165   <none>          9091/TCP,15004/TCP,15014/TCP,42422/TCP                                                                                                       25m
istio-system   service/promsd                   ClusterIP      10.20.12.72    <none>          9090/TCP                                                                                                                                     25m
kube-system    service/default-http-backend     NodePort       10.20.4.53     <none>          80:30095/TCP                                                                                                                                 26m
kube-system    service/heapster                 ClusterIP      10.20.9.0      <none>          80/TCP                                                                                                                                       26m
kube-system    service/kube-dns                 ClusterIP      10.20.0.10     <none>          53/UDP,53/TCP                                                                                                                                26m
kube-system    service/metrics-server           ClusterIP      10.20.6.243    <none>          443/TCP                                                                                                                                      26m

NAMESPACE     NAME                                      DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR                                  AGE
kube-system   daemonset.apps/fluentd-gcp-v3.1.1         3         3         3       3            3           beta.kubernetes.io/fluentd-ds-ready=true       26m
kube-system   daemonset.apps/metadata-proxy-v0.1        0         0         0       0            0           beta.kubernetes.io/metadata-proxy-ready=true   26m
kube-system   daemonset.apps/nvidia-gpu-device-plugin   0         0         0       0            0           <none>                                         26m
kube-system   daemonset.apps/prometheus-to-sd           3         3         3       3            3           beta.kubernetes.io/os=linux                    26m

NAMESPACE      NAME                                                       READY   UP-TO-DATE   AVAILABLE   AGE
istio-system   deployment.apps/istio-citadel                              1/1     1            1           26m
istio-system   deployment.apps/istio-galley                               1/1     1            1           26m
istio-system   deployment.apps/istio-ingressgateway                       1/1     1            1           26m
istio-system   deployment.apps/istio-pilot                                1/1     1            1           26m
istio-system   deployment.apps/istio-policy                               1/1     1            1           26m
istio-system   deployment.apps/istio-sidecar-injector                     1/1     1            1           26m
istio-system   deployment.apps/istio-telemetry                            1/1     1            1           26m
istio-system   deployment.apps/promsd                                     1/1     1            1           26m
kube-system    deployment.apps/event-exporter-v0.2.5                      1/1     1            1           26m
kube-system    deployment.apps/fluentd-gcp-scaler                         1/1     1            1           26m
kube-system    deployment.apps/heapster-v1.6.1                            1/1     1            1           26m
kube-system    deployment.apps/kube-dns                                   2/2     2            2           26m
kube-system    deployment.apps/kube-dns-autoscaler                        1/1     1            1           26m
kube-system    deployment.apps/l7-default-backend                         1/1     1            1           26m
kube-system    deployment.apps/metrics-server-v0.3.1                      1/1     1            1           26m
kube-system    deployment.apps/stackdriver-metadata-agent-cluster-level   1/1     1            1           26m

NAMESPACE      NAME                                                                  DESIRED   CURRENT   READY   AGE
istio-system   replicaset.apps/istio-citadel-5c88f4f47d                              1         1         1       26m
istio-system   replicaset.apps/istio-galley-6c78cdcfc4                               1         1         1       26m
istio-system   replicaset.apps/istio-ingressgateway-7f6db9967c                       1         1         1       26m
istio-system   replicaset.apps/istio-pilot-56df8c9cf6                                1         1         1       26m
istio-system   replicaset.apps/istio-policy-68775985b8                               1         1         1       26m
istio-system   replicaset.apps/istio-sidecar-injector-bc79fc549                      1         1         1       26m
istio-system   replicaset.apps/istio-telemetry-5965f9d996                            1         1         1       26m
istio-system   replicaset.apps/promsd-f876c8c55                                      1         1         1       26m
kube-system    replicaset.apps/event-exporter-v0.2.5-7d99d74cf8                      1         1         1       26m
kube-system    replicaset.apps/fluentd-gcp-scaler-55bdf597c                          1         1         1       26m
kube-system    replicaset.apps/heapster-v1.6.1-75c89cf597                            1         1         1       26m
kube-system    replicaset.apps/heapster-v1.6.1-75df5bc85                             0         0         0       26m
kube-system    replicaset.apps/kube-dns-6987857fdb                                   2         2         2       27m
kube-system    replicaset.apps/kube-dns-autoscaler-bb58c6784                         1         1         1       27m
kube-system    replicaset.apps/l7-default-backend-fd59995cd                          1         1         1       27m
kube-system    replicaset.apps/metrics-server-v0.3.1-57c75779f                       1         1         1       26m
kube-system    replicaset.apps/metrics-server-v0.3.1-c4cddd5f5                       0         0         0       26m
kube-system    replicaset.apps/stackdriver-metadata-agent-cluster-level-7b549bd965   1         1         1       26m

NAMESPACE      NAME                                                       REFERENCE                         TARGETS         MINPODS   MAXPODS   REPLICAS   AGE
istio-system   horizontalpodautoscaler.autoscaling/istio-ingressgateway   Deployment/istio-ingressgateway   <unknown>/80%   1         5         1          26m
istio-system   horizontalpodautoscaler.autoscaling/istio-pilot            Deployment/istio-pilot            <unknown>/80%   1         5         1          26m
istio-system   horizontalpodautoscaler.autoscaling/istio-policy           Deployment/istio-policy           <unknown>/80%   1         5         1          26m
istio-system   horizontalpodautoscaler.autoscaling/istio-telemetry        Deployment/istio-telemetry        <unknown>/80%   1         5         1          26m

NAMESPACE      NAME                                          COMPLETIONS   DURATION   AGE
istio-system   job.batch/istio-cleanup-secrets-1.1.3         1/1           23s        26m
istio-system   job.batch/istio-init-crd-10                   1/1           23s        26m
istio-system   job.batch/istio-init-crd-11                   1/1           31s        26m
istio-system   job.batch/istio-security-post-install-1.1.3   1/1           25s        26m
>>> Services:
NAMESPACE      NAME                     TYPE           CLUSTER-IP     EXTERNAL-IP     PORT(S)                                                                                                                                      AGE
default        kubernetes               ClusterIP      10.20.0.1      <none>          443/TCP                                                                                                                                      28m
istio-system   istio-citadel            ClusterIP      10.20.7.36     <none>          8060/TCP,15014/TCP                                                                                                                           26m
istio-system   istio-galley             ClusterIP      10.20.3.49     <none>          443/TCP,15014/TCP,9901/TCP                                                                                                                   26m
istio-system   istio-ingressgateway     LoadBalancer   10.20.12.139   34.83.198.217   15020:32744/TCP,80:31380/TCP,443:31390/TCP,31400:31400/TCP,15029:31099/TCP,15030:30804/TCP,15031:30428/TCP,15032:30766/TCP,15443:32692/TCP   26m
istio-system   istio-pilot              ClusterIP      10.20.12.244   <none>          15010/TCP,15011/TCP,8080/TCP,15014/TCP                                                                                                       26m
istio-system   istio-policy             ClusterIP      10.20.7.186    <none>          9091/TCP,15004/TCP,15014/TCP                                                                                                                 26m
istio-system   istio-sidecar-injector   ClusterIP      10.20.10.224   <none>          443/TCP                                                                                                                                      26m
istio-system   istio-telemetry          ClusterIP      10.20.14.165   <none>          9091/TCP,15004/TCP,15014/TCP,42422/TCP                                                                                                       26m
istio-system   promsd                   ClusterIP      10.20.12.72    <none>          9090/TCP                                                                                                                                     26m
kube-system    default-http-backend     NodePort       10.20.4.53     <none>          80:30095/TCP                                                                                                                                 27m
kube-system    heapster                 ClusterIP      10.20.9.0      <none>          80/TCP                                                                                                                                       26m
kube-system    kube-dns                 ClusterIP      10.20.0.10     <none>          53/UDP,53/TCP                                                                                                                                27m
kube-system    metrics-server           ClusterIP      10.20.6.243    <none>          443/TCP                                                                                                                                      26m
>>> Events:
NAMESPACE      LAST SEEN   TYPE      REASON                         KIND                      MESSAGE
default        26m         Normal    Starting                       Node                      Starting kubelet.
default        26m         Normal    NodeHasSufficientMemory        Node                      Node gke-knative-default-pool-0b861d45-bb9t status is now: NodeHasSufficientMemory
default        26m         Normal    NodeHasNoDiskPressure          Node                      Node gke-knative-default-pool-0b861d45-bb9t status is now: NodeHasNoDiskPressure
default        26m         Normal    NodeHasSufficientPID           Node                      Node gke-knative-default-pool-0b861d45-bb9t status is now: NodeHasSufficientPID
default        26m         Normal    NodeAllocatableEnforced        Node                      Updated Node Allocatable limit across pods
default        26m         Normal    NodeReady                      Node                      Node gke-knative-default-pool-0b861d45-bb9t status is now: NodeReady
default        26m         Normal    Starting                       Node                      Starting kube-proxy.
default        26m         Normal    RegisteredNode                 Node                      Node gke-knative-default-pool-0b861d45-bb9t event: Registered Node gke-knative-default-pool-0b861d45-bb9t in Controller
default        24m         Normal    FrequentKubeletRestart         Node                      Node condition FrequentKubeletRestart is now: False, reason: FrequentKubeletRestart
default        24m         Normal    CorruptDockerOverlay2          Node                      Node condition CorruptDockerOverlay2 is now: False, reason: CorruptDockerOverlay2
default        24m         Normal    UnregisterNetDevice            Node                      Node condition FrequentUnregisterNetDevice is now: False, reason: UnregisterNetDevice
default        24m         Normal    FrequentDockerRestart          Node                      Node condition FrequentDockerRestart is now: False, reason: FrequentDockerRestart
default        24m         Normal    FrequentContainerdRestart      Node                      Node condition FrequentContainerdRestart is now: False, reason: FrequentContainerdRestart
default        26m         Normal    Starting                       Node                      Starting kubelet.
default        26m         Normal    NodeHasSufficientMemory        Node                      Node gke-knative-default-pool-0b861d45-bs83 status is now: NodeHasSufficientMemory
default        26m         Normal    NodeHasNoDiskPressure          Node                      Node gke-knative-default-pool-0b861d45-bs83 status is now: NodeHasNoDiskPressure
default        26m         Normal    NodeHasSufficientPID           Node                      Node gke-knative-default-pool-0b861d45-bs83 status is now: NodeHasSufficientPID
default        26m         Normal    NodeAllocatableEnforced        Node                      Updated Node Allocatable limit across pods
default        26m         Normal    NodeReady                      Node                      Node gke-knative-default-pool-0b861d45-bs83 status is now: NodeReady
default        26m         Normal    Starting                       Node                      Starting kube-proxy.
default        26m         Normal    RegisteredNode                 Node                      Node gke-knative-default-pool-0b861d45-bs83 event: Registered Node gke-knative-default-pool-0b861d45-bs83 in Controller
default        24m         Normal    CorruptDockerOverlay2          Node                      Node condition CorruptDockerOverlay2 is now: False, reason: CorruptDockerOverlay2
default        24m         Normal    FrequentKubeletRestart         Node                      Node condition FrequentKubeletRestart is now: False, reason: FrequentKubeletRestart
default        24m         Normal    UnregisterNetDevice            Node                      Node condition FrequentUnregisterNetDevice is now: False, reason: UnregisterNetDevice
default        24m         Normal    FrequentDockerRestart          Node                      Node condition FrequentDockerRestart is now: False, reason: FrequentDockerRestart
default        24m         Normal    FrequentContainerdRestart      Node                      Node condition FrequentContainerdRestart is now: False, reason: FrequentContainerdRestart
default        26m         Normal    Starting                       Node                      Starting kubelet.
default        26m         Normal    NodeHasSufficientMemory        Node                      Node gke-knative-default-pool-0b861d45-pvmn status is now: NodeHasSufficientMemory
default        26m         Normal    NodeHasNoDiskPressure          Node                      Node gke-knative-default-pool-0b861d45-pvmn status is now: NodeHasNoDiskPressure
default        26m         Normal    NodeHasSufficientPID           Node                      Node gke-knative-default-pool-0b861d45-pvmn status is now: NodeHasSufficientPID
default        26m         Normal    NodeAllocatableEnforced        Node                      Updated Node Allocatable limit across pods
default        26m         Normal    NodeReady                      Node                      Node gke-knative-default-pool-0b861d45-pvmn status is now: NodeReady
default        26m         Normal    Starting                       Node                      Starting kube-proxy.
default        26m         Normal    RegisteredNode                 Node                      Node gke-knative-default-pool-0b861d45-pvmn event: Registered Node gke-knative-default-pool-0b861d45-pvmn in Controller
default        24m         Normal    FrequentKubeletRestart         Node                      Node condition FrequentKubeletRestart is now: False, reason: FrequentKubeletRestart
default        24m         Normal    CorruptDockerOverlay2          Node                      Node condition CorruptDockerOverlay2 is now: False, reason: CorruptDockerOverlay2
default        24m         Normal    UnregisterNetDevice            Node                      Node condition FrequentUnregisterNetDevice is now: False, reason: UnregisterNetDevice
default        24m         Normal    FrequentDockerRestart          Node                      Node condition FrequentDockerRestart is now: False, reason: FrequentDockerRestart
default        24m         Normal    FrequentContainerdRestart      Node                      Node condition FrequentContainerdRestart is now: False, reason: FrequentContainerdRestart
istio-system   26m         Normal    Scheduled                      Pod                       Successfully assigned istio-system/istio-citadel-5c88f4f47d-tghsm to gke-knative-default-pool-0b861d45-bs83
istio-system   26m         Normal    Pulling                        Pod                       pulling image "gcr.io/gke-release/istio/citadel:1.1.3-gke.0"
istio-system   26m         Normal    Pulled                         Pod                       Successfully pulled image "gcr.io/gke-release/istio/citadel:1.1.3-gke.0"
istio-system   26m         Normal    Created                        Pod                       Created container
istio-system   26m         Normal    Started                        Pod                       Started container
istio-system   26m         Normal    SuccessfulCreate               ReplicaSet                Created pod: istio-citadel-5c88f4f47d-tghsm
istio-system   26m         Normal    ScalingReplicaSet              Deployment                Scaled up replica set istio-citadel-5c88f4f47d to 1
istio-system   26m         Normal    Scheduled                      Pod                       Successfully assigned istio-system/istio-cleanup-secrets-1.1.3-qxnpr to gke-knative-default-pool-0b861d45-bb9t
istio-system   26m         Normal    Pulling                        Pod                       pulling image "gcr.io/gke-release/istio/kubectl:1.1.3-gke.0"
istio-system   26m         Normal    Pulled                         Pod                       Successfully pulled image "gcr.io/gke-release/istio/kubectl:1.1.3-gke.0"
istio-system   26m         Normal    Created                        Pod                       Created container
istio-system   26m         Normal    Started                        Pod                       Started container
istio-system   26m         Normal    SuccessfulCreate               Job                       Created pod: istio-cleanup-secrets-1.1.3-qxnpr
istio-system   26m         Normal    Scheduled                      Pod                       Successfully assigned istio-system/istio-galley-6c78cdcfc4-g2b5w to gke-knative-default-pool-0b861d45-bb9t
istio-system   26m         Warning   FailedMount                    Pod                       MountVolume.SetUp failed for volume "certs" : secrets "istio.istio-galley-service-account" not found
istio-system   25m         Normal    Pulling                        Pod                       pulling image "gcr.io/gke-release/istio/galley:1.1.3-gke.0"
istio-system   25m         Normal    Pulled                         Pod                       Successfully pulled image "gcr.io/gke-release/istio/galley:1.1.3-gke.0"
istio-system   25m         Normal    Created                        Pod                       Created container
istio-system   25m         Normal    Started                        Pod                       Started container
istio-system   26m         Normal    SuccessfulCreate               ReplicaSet                Created pod: istio-galley-6c78cdcfc4-g2b5w
istio-system   26m         Normal    NoPods                         PodDisruptionBudget       No matching pods found
istio-system   26m         Normal    ScalingReplicaSet              Deployment                Scaled up replica set istio-galley-6c78cdcfc4 to 1
istio-system   26m         Normal    Scheduled                      Pod                       Successfully assigned istio-system/istio-ingressgateway-7f6db9967c-v6dqs to gke-knative-default-pool-0b861d45-bs83
istio-system   26m         Normal    Pulling                        Pod                       pulling image "gcr.io/gke-release/istio/proxyv2:1.1.3-gke.0"
istio-system   26m         Normal    Pulled                         Pod                       Successfully pulled image "gcr.io/gke-release/istio/proxyv2:1.1.3-gke.0"
istio-system   26m         Normal    Created                        Pod                       Created container
istio-system   26m         Normal    Started                        Pod                       Started container
istio-system   25m         Warning   Unhealthy                      Pod                       Readiness probe failed: HTTP probe failed with statuscode: 503
istio-system   26m         Normal    SuccessfulCreate               ReplicaSet                Created pod: istio-ingressgateway-7f6db9967c-v6dqs
istio-system   26m         Normal    NoPods                         PodDisruptionBudget       No matching pods found
istio-system   26m         Normal    ScalingReplicaSet              Deployment                Scaled up replica set istio-ingressgateway-7f6db9967c to 1
istio-system   26m         Normal    EnsuringLoadBalancer           Service                   Ensuring load balancer
istio-system   25m         Warning   FailedGetResourceMetric        HorizontalPodAutoscaler   unable to get metrics for resource cpu: no metrics returned from resource metrics API
istio-system   25m         Warning   FailedComputeMetricsReplicas   HorizontalPodAutoscaler   failed to get cpu utilization: unable to get metrics for resource cpu: no metrics returned from resource metrics API
istio-system   25m         Normal    UpdatedLoadBalancer            Service                   Updated load balancer with new hosts
istio-system   40s         Warning   FailedGetResourceMetric        HorizontalPodAutoscaler   missing request for cpu
istio-system   23m         Warning   FailedComputeMetricsReplicas   HorizontalPodAutoscaler   failed to get cpu utilization: missing request for cpu
istio-system   25m         Normal    EnsuredLoadBalancer            Service                   Ensured load balancer
istio-system   26m         Normal    Scheduled                      Pod                       Successfully assigned istio-system/istio-init-crd-10-7mkmj to gke-knative-default-pool-0b861d45-bb9t
istio-system   26m         Normal    Pulling                        Pod                       pulling image "gcr.io/gke-release/istio/kubectl:1.1.3-gke.0"
istio-system   26m         Normal    Pulled                         Pod                       Successfully pulled image "gcr.io/gke-release/istio/kubectl:1.1.3-gke.0"
istio-system   26m         Normal    Created                        Pod                       Created container
istio-system   26m         Normal    Started                        Pod                       Started container
istio-system   26m         Normal    SuccessfulCreate               Job                       Created pod: istio-init-crd-10-7mkmj
istio-system   26m         Normal    Scheduled                      Pod                       Successfully assigned istio-system/istio-init-crd-11-gwkd5 to gke-knative-default-pool-0b861d45-bs83
istio-system   26m         Normal    Pulling                        Pod                       pulling image "gcr.io/gke-release/istio/kubectl:1.1.3-gke.0"
istio-system   26m         Normal    Pulled                         Pod                       Successfully pulled image "gcr.io/gke-release/istio/kubectl:1.1.3-gke.0"
istio-system   26m         Normal    Created                        Pod                       Created container
istio-system   26m         Normal    Started                        Pod                       Started container
istio-system   26m         Normal    SuccessfulCreate               Job                       Created pod: istio-init-crd-11-gwkd5
istio-system   26m         Normal    Scheduled                      Pod                       Successfully assigned istio-system/istio-pilot-56df8c9cf6-2m94q to gke-knative-default-pool-0b861d45-bs83
istio-system   26m         Normal    Pulling                        Pod                       pulling image "gcr.io/gke-release/istio/pilot:1.1.3-gke.0"
istio-system   26m         Normal    Pulled                         Pod                       Successfully pulled image "gcr.io/gke-release/istio/pilot:1.1.3-gke.0"
istio-system   26m         Normal    Created                        Pod                       Created container
istio-system   26m         Normal    Started                        Pod                       Started container
istio-system   26m         Normal    Pulled                         Pod                       Container image "gcr.io/gke-release/istio/proxyv2:1.1.3-gke.0" already present on machine
istio-system   26m         Normal    Created                        Pod                       Created container
istio-system   26m         Normal    Started                        Pod                       Started container
istio-system   25m         Warning   Unhealthy                      Pod                       Readiness probe failed: Get http://10.16.1.8:8080/ready: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
istio-system   26m         Normal    SuccessfulCreate               ReplicaSet                Created pod: istio-pilot-56df8c9cf6-2m94q
istio-system   26m         Normal    NoPods                         PodDisruptionBudget       No matching pods found
istio-system   26m         Normal    ScalingReplicaSet              Deployment                Scaled up replica set istio-pilot-56df8c9cf6 to 1
istio-system   25m         Warning   FailedGetResourceMetric        HorizontalPodAutoscaler   unable to get metrics for resource cpu: no metrics returned from resource metrics API
istio-system   25m         Warning   FailedComputeMetricsReplicas   HorizontalPodAutoscaler   failed to get cpu utilization: unable to get metrics for resource cpu: no metrics returned from resource metrics API
istio-system   40s         Warning   FailedGetResourceMetric        HorizontalPodAutoscaler   missing request for cpu
istio-system   23m         Warning   FailedComputeMetricsReplicas   HorizontalPodAutoscaler   failed to get cpu utilization: missing request for cpu
istio-system   26m         Normal    Scheduled                      Pod                       Successfully assigned istio-system/istio-policy-68775985b8-67gmw to gke-knative-default-pool-0b861d45-bb9t
istio-system   26m         Normal    Pulling                        Pod                       pulling image "gcr.io/gke-release/istio/mixer:1.1.3-gke.0"
istio-system   26m         Normal    Pulled                         Pod                       Successfully pulled image "gcr.io/gke-release/istio/mixer:1.1.3-gke.0"
istio-system   25m         Normal    Created                        Pod                       Created container
istio-system   25m         Normal    Started                        Pod                       Started container
istio-system   26m         Normal    Pulling                        Pod                       pulling image "gcr.io/gke-release/istio/proxyv2:1.1.3-gke.0"
istio-system   26m         Normal    Pulled                         Pod                       Successfully pulled image "gcr.io/gke-release/istio/proxyv2:1.1.3-gke.0"
istio-system   26m         Normal    Created                        Pod                       Created container
istio-system   26m         Normal    Started                        Pod                       Started container
istio-system   25m         Warning   Unhealthy                      Pod                       Liveness probe failed: Get http://10.16.0.5:15014/version: dial tcp 10.16.0.5:15014: connect: connection refused
istio-system   25m         Normal    Killing                        Pod                       Killing container with id docker://mixer:Container failed liveness probe.. Container will be killed and recreated.
istio-system   25m         Normal    Pulled                         Pod                       Container image "gcr.io/gke-release/istio/mixer:1.1.3-gke.0" already present on machine
istio-system   26m         Normal    SuccessfulCreate               ReplicaSet                Created pod: istio-policy-68775985b8-67gmw
istio-system   26m         Normal    NoPods                         PodDisruptionBudget       No matching pods found
istio-system   26m         Normal    ScalingReplicaSet              Deployment                Scaled up replica set istio-policy-68775985b8 to 1
istio-system   25m         Warning   FailedGetResourceMetric        HorizontalPodAutoscaler   unable to get metrics for resource cpu: no metrics returned from resource metrics API
istio-system   25m         Warning   FailedComputeMetricsReplicas   HorizontalPodAutoscaler   failed to get cpu utilization: unable to get metrics for resource cpu: no metrics returned from resource metrics API
istio-system   40s         Warning   FailedGetResourceMetric        HorizontalPodAutoscaler   missing request for cpu
istio-system   23m         Warning   FailedComputeMetricsReplicas   HorizontalPodAutoscaler   failed to get cpu utilization: missing request for cpu
istio-system   26m         Normal    Scheduled                      Pod                       Successfully assigned istio-system/istio-security-post-install-1.1.3-whz95 to gke-knative-default-pool-0b861d45-bb9t
istio-system   26m         Normal    Pulling                        Pod                       pulling image "gcr.io/gke-release/istio/kubectl:1.1.3-gke.0"
istio-system   26m         Normal    Pulled                         Pod                       Successfully pulled image "gcr.io/gke-release/istio/kubectl:1.1.3-gke.0"
istio-system   26m         Normal    Created                        Pod                       Created container
istio-system   26m         Normal    Started                        Pod                       Started container
istio-system   26m         Normal    SuccessfulCreate               Job                       Created pod: istio-security-post-install-1.1.3-whz95
istio-system   26m         Normal    Scheduled                      Pod                       Successfully assigned istio-system/istio-sidecar-injector-bc79fc549-qmckw to gke-knative-default-pool-0b861d45-bb9t
istio-system   26m         Warning   FailedMount                    Pod                       MountVolume.SetUp failed for volume "certs" : secrets "istio.istio-sidecar-injector-service-account" not found
istio-system   25m         Normal    Pulling                        Pod                       pulling image "gcr.io/gke-release/istio/sidecar_injector:1.1.3-gke.0"
istio-system   25m         Normal    Pulled                         Pod                       Successfully pulled image "gcr.io/gke-release/istio/sidecar_injector:1.1.3-gke.0"
istio-system   25m         Normal    Created                        Pod                       Created container
istio-system   25m         Normal    Started                        Pod                       Started container
istio-system   26m         Normal    SuccessfulCreate               ReplicaSet                Created pod: istio-sidecar-injector-bc79fc549-qmckw
istio-system   26m         Normal    ScalingReplicaSet              Deployment                Scaled up replica set istio-sidecar-injector-bc79fc549 to 1
istio-system   26m         Normal    Scheduled                      Pod                       Successfully assigned istio-system/istio-telemetry-5965f9d996-687c8 to gke-knative-default-pool-0b861d45-bb9t
istio-system   26m         Normal    Pulling                        Pod                       pulling image "gcr.io/gke-release/istio/mixer:1.1.3-gke.0"
istio-system   26m         Normal    Pulled                         Pod                       Successfully pulled image "gcr.io/gke-release/istio/mixer:1.1.3-gke.0"
istio-system   25m         Normal    Created                        Pod                       Created container
istio-system   25m         Normal    Started                        Pod                       Started container
istio-system   26m         Normal    Pulling                        Pod                       pulling image "gcr.io/gke-release/istio/proxyv2:1.1.3-gke.0"
istio-system   26m         Normal    Pulled                         Pod                       Successfully pulled image "gcr.io/gke-release/istio/proxyv2:1.1.3-gke.0"
istio-system   26m         Normal    Created                        Pod                       Created container
istio-system   26m         Normal    Started                        Pod                       Started container
istio-system   25m         Warning   Unhealthy                      Pod                       Liveness probe failed: Get http://10.16.0.6:15014/version: dial tcp 10.16.0.6:15014: connect: connection refused
istio-system   25m         Normal    Killing                        Pod                       Killing container with id docker://mixer:Container failed liveness probe.. Container will be killed and recreated.
istio-system   25m         Normal    Pulled                         Pod                       Container image "gcr.io/gke-release/istio/mixer:1.1.3-gke.0" already present on machine
istio-system   26m         Normal    SuccessfulCreate               ReplicaSet                Created pod: istio-telemetry-5965f9d996-687c8
istio-system   26m         Normal    NoPods                         PodDisruptionBudget       No matching pods found
istio-system   26m         Normal    ScalingReplicaSet              Deployment                Scaled up replica set istio-telemetry-5965f9d996 to 1
istio-system   25m         Warning   FailedGetResourceMetric        HorizontalPodAutoscaler   unable to get metrics for resource cpu: no metrics returned from resource metrics API
istio-system   25m         Warning   FailedComputeMetricsReplicas   HorizontalPodAutoscaler   failed to get cpu utilization: unable to get metrics for resource cpu: no metrics returned from resource metrics API
istio-system   40s         Warning   FailedGetResourceMetric        HorizontalPodAutoscaler   missing request for cpu
istio-system   23m         Warning   FailedComputeMetricsReplicas   HorizontalPodAutoscaler   failed to get cpu utilization: missing request for cpu
istio-system   26m         Normal    Scheduled                      Pod                       Successfully assigned istio-system/promsd-f876c8c55-n92lc to gke-knative-default-pool-0b861d45-pvmn
istio-system   26m         Normal    Pulling                        Pod                       pulling image "gcr.io/gke-release/istio/prometheus/stackdriver-prometheus-sidecar:0.1"
istio-system   26m         Normal    Pulled                         Pod                       Successfully pulled image "gcr.io/gke-release/istio/prometheus/stackdriver-prometheus-sidecar:0.1"
istio-system   26m         Normal    Created                        Pod                       Created container
istio-system   26m         Normal    Started                        Pod                       Started container
istio-system   26m         Normal    Pulling                        Pod                       pulling image "gcr.io/gke-release/istio/prometheus/prometheus:v2.4.3"
istio-system   26m         Normal    Pulled                         Pod                       Successfully pulled image "gcr.io/gke-release/istio/prometheus/prometheus:v2.4.3"
istio-system   26m         Normal    Created                        Pod                       Created container
istio-system   26m         Normal    Started                        Pod                       Started container
istio-system   26m         Normal    SuccessfulCreate               ReplicaSet                Created pod: promsd-f876c8c55-n92lc
istio-system   26m         Normal    ScalingReplicaSet              Deployment                Scaled up replica set promsd-f876c8c55 to 1
kube-system    26m         Normal    LeaderElection                 Endpoints                 gke-f13d7152c1efe40b1782-b466-7a2c-vm became leader
kube-system    26m         Warning   FailedScheduling               Pod                       no nodes available to schedule pods
kube-system    26m         Normal    Scheduled                      Pod                       Successfully assigned kube-system/event-exporter-v0.2.5-7d99d74cf8-n5rg4 to gke-knative-default-pool-0b861d45-bs83
kube-system    26m         Warning   NetworkNotReady                Pod                       network is not ready: [runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: Kubenet does not have netConfig. This is most likely due to lack of PodCIDR]
kube-system    26m         Normal    Pulling                        Pod                       pulling image "k8s.gcr.io/event-exporter:v0.2.5"
kube-system    26m         Normal    Pulled                         Pod                       Successfully pulled image "k8s.gcr.io/event-exporter:v0.2.5"
kube-system    26m         Normal    Created                        Pod                       Created container
kube-system    26m         Normal    Started                        Pod                       Started container
kube-system    26m         Normal    Pulled                         Pod                       Container image "k8s.gcr.io/prometheus-to-sd:v0.5.0" already present on machine
kube-system    26m         Normal    Created                        Pod                       Created container
kube-system    26m         Normal    Started                        Pod                       Started container
kube-system    27m         Normal    SuccessfulCreate               ReplicaSet                Created pod: event-exporter-v0.2.5-7d99d74cf8-n5rg4
kube-system    27m         Normal    ScalingReplicaSet              Deployment                Scaled up replica set event-exporter-v0.2.5-7d99d74cf8 to 1
kube-system    26m         Normal    Scheduled                      Pod                       Successfully assigned kube-system/fluentd-gcp-scaler-55bdf597c-2xhbz to gke-knative-default-pool-0b861d45-bs83
kube-system    26m         Normal    Pulling                        Pod                       pulling image "k8s.gcr.io/fluentd-gcp-scaler:0.5.1"
kube-system    26m         Normal    Pulled                         Pod                       Successfully pulled image "k8s.gcr.io/fluentd-gcp-scaler:0.5.1"
kube-system    26m         Normal    Created                        Pod                       Created container
kube-system    26m         Normal    Started                        Pod                       Started container
kube-system    26m         Normal    SuccessfulCreate               ReplicaSet                Created pod: fluentd-gcp-scaler-55bdf597c-2xhbz
kube-system    26m         Normal    ScalingReplicaSet              Deployment                Scaled up replica set fluentd-gcp-scaler-55bdf597c to 1
kube-system    25m         Normal    Scheduled                      Pod                       Successfully assigned kube-system/fluentd-gcp-v3.1.1-4b84l to gke-knative-default-pool-0b861d45-pvmn
kube-system    25m         Normal    Pulled                         Pod                       Container image "gcr.io/stackdriver-agents/stackdriver-logging-agent:1.6.6" already present on machine
kube-system    25m         Normal    Created                        Pod                       Created container
kube-system    25m         Normal    Started                        Pod                       Started container
kube-system    25m         Normal    Pulled                         Pod                       Container image "k8s.gcr.io/prometheus-to-sd:v0.5.0" already present on machine
kube-system    25m         Normal    Created                        Pod                       Created container
kube-system    25m         Normal    Started                        Pod                       Started container
kube-system    26m         Normal    Scheduled                      Pod                       Successfully assigned kube-system/fluentd-gcp-v3.1.1-7wwcq to gke-knative-default-pool-0b861d45-bb9t
kube-system    26m         Warning   FailedMount                    Pod                       MountVolume.SetUp failed for volume "config-volume" : configmaps "fluentd-gcp-config-v1.2.6" not found
kube-system    26m         Normal    Pulling                        Pod                       pulling image "gcr.io/stackdriver-agents/stackdriver-logging-agent:1.6.6"
kube-system    26m         Normal    Pulled                         Pod                       Successfully pulled image "gcr.io/stackdriver-agents/stackdriver-logging-agent:1.6.6"
kube-system    26m         Normal    Created                        Pod                       Created container
kube-system    26m         Normal    Started                        Pod                       Started container
kube-system    26m         Normal    Pulled                         Pod                       Container image "k8s.gcr.io/prometheus-to-sd:v0.5.0" already present on machine
kube-system    26m         Normal    Created                        Pod                       Created container
kube-system    26m         Normal    Started                        Pod                       Started container
kube-system    25m         Normal    Killing                        Pod                       Killing container with id docker://prometheus-to-sd-exporter:Need to kill Pod
kube-system    25m         Normal    Killing                        Pod                       Killing container with id docker://fluentd-gcp:Need to kill Pod
kube-system    26m         Normal    Scheduled                      Pod                       Successfully assigned kube-system/fluentd-gcp-v3.1.1-g5blh to gke-knative-default-pool-0b861d45-bs83
kube-system    26m         Warning   FailedMount                    Pod                       MountVolume.SetUp failed for volume "config-volume" : configmaps "fluentd-gcp-config-v1.2.6" not found
kube-system    26m         Normal    Pulling                        Pod                       pulling image "gcr.io/stackdriver-agents/stackdriver-logging-agent:1.6.6"
kube-system    26m         Normal    Pulled                         Pod                       Successfully pulled image "gcr.io/stackdriver-agents/stackdriver-logging-agent:1.6.6"
kube-system    26m         Normal    Created                        Pod                       Created container
kube-system    26m         Normal    Started                        Pod                       Started container
kube-system    26m         Normal    Pulled                         Pod                       Container image "k8s.gcr.io/prometheus-to-sd:v0.5.0" already present on machine
kube-system    26m         Normal    Created                        Pod                       Created container
kube-system    26m         Normal    Started                        Pod                       Started container
kube-system    26m         Normal    Killing                        Pod                       Killing container with id docker://fluentd-gcp:Need to kill Pod
kube-system    26m         Normal    Killing                        Pod                       Killing container with id docker://prometheus-to-sd-exporter:Need to kill Pod
kube-system    26m         Normal    Scheduled                      Pod                       Successfully assigned kube-system/fluentd-gcp-v3.1.1-m4x5j to gke-knative-default-pool-0b861d45-pvmn
kube-system    26m         Warning   FailedMount                    Pod                       MountVolume.SetUp failed for volume "config-volume" : configmaps "fluentd-gcp-config-v1.2.6" not found
kube-system    26m         Normal    Pulling                        Pod                       pulling image "gcr.io/stackdriver-agents/stackdriver-logging-agent:1.6.6"
kube-system    26m         Normal    Pulled                         Pod                       Successfully pulled image "gcr.io/stackdriver-agents/stackdriver-logging-agent:1.6.6"
kube-system    26m         Normal    Created                        Pod                       Created container
kube-system    26m         Normal    Started                        Pod                       Started container
kube-system    26m         Normal    Pulled                         Pod                       Container image "k8s.gcr.io/prometheus-to-sd:v0.5.0" already present on machine
kube-system    26m         Normal    Created                        Pod                       Created container
kube-system    26m         Normal    Started                        Pod                       Started container
kube-system    25m         Normal    Killing                        Pod                       Killing container with id docker://prometheus-to-sd-exporter:Need to kill Pod
kube-system    25m         Normal    Killing                        Pod                       Killing container with id docker://fluentd-gcp:Need to kill Pod
kube-system    25m         Normal    Scheduled                      Pod                       Successfully assigned kube-system/fluentd-gcp-v3.1.1-t44rj to gke-knative-default-pool-0b861d45-bb9t
kube-system    25m         Normal    Pulled                         Pod                       Container image "gcr.io/stackdriver-agents/stackdriver-logging-agent:1.6.6" already present on machine
kube-system    25m         Normal    Created                        Pod                       Created container
kube-system    25m         Normal    Started                        Pod                       Started container
kube-system    25m         Normal    Pulled                         Pod                       Container image "k8s.gcr.io/prometheus-to-sd:v0.5.0" already present on machine
kube-system    25m         Normal    Created                        Pod                       Created container
kube-system    25m         Normal    Started                        Pod                       Started container
kube-system    25m         Normal    Scheduled                      Pod                       Successfully assigned kube-system/fluentd-gcp-v3.1.1-z7znh to gke-knative-default-pool-0b861d45-bs83
kube-system    25m         Normal    Pulled                         Pod                       Container image "gcr.io/stackdriver-agents/stackdriver-logging-agent:1.6.6" already present on machine
kube-system    25m         Normal    Created                        Pod                       Created container
kube-system    25m         Normal    Started                        Pod                       Started container
kube-system    25m         Normal    Pulled                         Pod                       Container image "k8s.gcr.io/prometheus-to-sd:v0.5.0" already present on machine
kube-system    25m         Normal    Created                        Pod                       Created container
kube-system    25m         Normal    Started                        Pod                       Started container
kube-system    26m         Normal    SuccessfulCreate               DaemonSet                 Created pod: fluentd-gcp-v3.1.1-m4x5j
kube-system    26m         Normal    SuccessfulCreate               DaemonSet                 Created pod: fluentd-gcp-v3.1.1-g5blh
kube-system    26m         Normal    SuccessfulCreate               DaemonSet                 Created pod: fluentd-gcp-v3.1.1-7wwcq
kube-system    26m         Normal    SuccessfulDelete               DaemonSet                 Deleted pod: fluentd-gcp-v3.1.1-g5blh
kube-system    25m         Normal    SuccessfulCreate               DaemonSet                 Created pod: fluentd-gcp-v3.1.1-z7znh
kube-system    25m         Normal    SuccessfulDelete               DaemonSet                 Deleted pod: fluentd-gcp-v3.1.1-m4x5j
kube-system    25m         Normal    SuccessfulCreate               DaemonSet                 Created pod: fluentd-gcp-v3.1.1-4b84l
kube-system    25m         Normal    SuccessfulDelete               DaemonSet                 Deleted pod: fluentd-gcp-v3.1.1-7wwcq
kube-system    25m         Normal    SuccessfulCreate               DaemonSet                 Created pod: fluentd-gcp-v3.1.1-t44rj
kube-system    27m         Normal    LeaderElection                 Endpoints                 gke-f13d7152c1efe40b1782-b466-7a2c-vm became leader
kube-system    27m         Normal    LeaderElection                 Endpoints                 gke-f13d7152c1efe40b1782-b466-7a2c-vm became leader
kube-system    28m         Normal    LeaderElection                 ConfigMap                 gke-f13d7152c1efe40b1782-b466-7a2c-vm_799a1 became leader
kube-system    27m         Normal    LeaderElection                 ConfigMap                 gke-f13d7152c1efe40b1782-b466-7a2c-vm_799a1 became leader
kube-system    26m         Normal    Scheduled                      Pod                       Successfully assigned kube-system/heapster-v1.6.1-75c89cf597-xwcr4 to gke-knative-default-pool-0b861d45-bs83
kube-system    26m         Normal    Pulling                        Pod                       pulling image "gcr.io/stackdriver-agents/heapster-amd64:v1.6.1"
kube-system    25m         Normal    Pulled                         Pod                       Successfully pulled image "gcr.io/stackdriver-agents/heapster-amd64:v1.6.1"
kube-system    25m         Normal    Created                        Pod                       Created container
kube-system    25m         Normal    Started                        Pod                       Started container
kube-system    25m         Normal    Pulled                         Pod                       Container image "k8s.gcr.io/prometheus-to-sd:v0.5.0" already present on machine
kube-system    25m         Normal    Created                        Pod                       Created container
kube-system    25m         Normal    Started                        Pod                       Started container
kube-system    25m         Normal    Pulling                        Pod                       pulling image "k8s.gcr.io/addon-resizer:1.8.3"
kube-system    25m         Normal    Pulled                         Pod                       Successfully pulled image "k8s.gcr.io/addon-resizer:1.8.3"
kube-system    25m         Normal    Created                        Pod                       Created container
kube-system    25m         Normal    Started                        Pod                       Started container
kube-system    26m         Normal    SuccessfulCreate               ReplicaSet                Created pod: heapster-v1.6.1-75c89cf597-xwcr4
kube-system    26m         Warning   FailedScheduling               Pod                       no nodes available to schedule pods
kube-system    26m         Normal    Scheduled                      Pod                       Successfully assigned kube-system/heapster-v1.6.1-75df5bc85-px7zr to gke-knative-default-pool-0b861d45-pvmn
kube-system    26m         Warning   NetworkNotReady                Pod                       network is not ready: [runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: Kubenet does not have netConfig. This is most likely due to lack of PodCIDR]
kube-system    26m         Normal    Pulling                        Pod                       pulling image "gcr.io/stackdriver-agents/heapster-amd64:v1.6.1"
kube-system    26m         Normal    Pulled                         Pod                       Successfully pulled image "gcr.io/stackdriver-agents/heapster-amd64:v1.6.1"
kube-system    26m         Normal    Created                        Pod                       Created container
kube-system    26m         Normal    Started                        Pod                       Started container
kube-system    26m         Normal    Pulled                         Pod                       Container image "k8s.gcr.io/prometheus-to-sd:v0.5.0" already present on machine
kube-system    26m         Normal    Created                        Pod                       Created container
kube-system    26m         Normal    Started                        Pod                       Started container
kube-system    26m         Normal    Pulling                        Pod                       pulling image "k8s.gcr.io/addon-resizer:1.8.3"
kube-system    26m         Normal    Pulled                         Pod                       Successfully pulled image "k8s.gcr.io/addon-resizer:1.8.3"
kube-system    26m         Normal    Created                        Pod                       Created container
kube-system    26m         Normal    Started                        Pod                       Started container
kube-system    26m         Normal    Killing                        Pod                       Killing container with id docker://prom-to-sd:Need to kill Pod
kube-system    26m         Normal    Killing                        Pod                       Killing container with id docker://heapster:Need to kill Pod
kube-system    26m         Normal    Killing                        Pod                       Killing container with id docker://heapster-nanny:Need to kill Pod
kube-system    27m         Normal    SuccessfulCreate               ReplicaSet                Created pod: heapster-v1.6.1-75df5bc85-px7zr
kube-system    26m         Normal    SuccessfulDelete               ReplicaSet                Deleted pod: heapster-v1.6.1-75df5bc85-px7zr
kube-system    27m         Normal    ScalingReplicaSet              Deployment                Scaled up replica set heapster-v1.6.1-75df5bc85 to 1
kube-system    26m         Normal    ScalingReplicaSet              Deployment                Scaled up replica set heapster-v1.6.1-75c89cf597 to 1
kube-system    26m         Normal    ScalingReplicaSet              Deployment                Scaled down replica set heapster-v1.6.1-75df5bc85 to 0
kube-system    27m         Normal    LeaderElection                 ConfigMap                 gke-f13d7152c1efe40b1782-b466-7a2c-vm_6eed2 became leader
kube-system    28m         Normal    LeaderElection                 Endpoints                 gke-f13d7152c1efe40b1782-b466-7a2c-vm_854b8d71-8b27-11e9-9099-42010a8a0095 became leader
kube-system    27m         Normal    LeaderElection                 Endpoints                 gke-f13d7152c1efe40b1782-b466-7a2c-vm_a7ea6568-8b27-11e9-8862-42010a8a0095 became leader
kube-system    26m         Normal    Scheduled                      Pod                       Successfully assigned kube-system/kube-dns-6987857fdb-gpvkc to gke-knative-default-pool-0b861d45-bb9t
kube-system    26m         Normal    Pulling                        Pod                       pulling image "k8s.gcr.io/k8s-dns-kube-dns-amd64:1.14.13"
kube-system    26m         Normal    Pulled                         Pod                       Successfully pulled image "k8s.gcr.io/k8s-dns-kube-dns-amd64:1.14.13"
kube-system    26m         Normal    Created                        Pod                       Created container
kube-system    26m         Normal    Started                        Pod                       Started container
kube-system    26m         Normal    Pulling                        Pod                       pulling image "k8s.gcr.io/k8s-dns-dnsmasq-nanny-amd64:1.14.13"
kube-system    26m         Normal    Pulled                         Pod                       Successfully pulled image "k8s.gcr.io/k8s-dns-dnsmasq-nanny-amd64:1.14.13"
kube-system    26m         Normal    Created                        Pod                       Created container
kube-system    26m         Normal    Started                        Pod                       Started container
kube-system    26m         Normal    Pulling                        Pod                       pulling image "k8s.gcr.io/k8s-dns-sidecar-amd64:1.14.13"
kube-system    26m         Normal    Pulled                         Pod                       Successfully pulled image "k8s.gcr.io/k8s-dns-sidecar-amd64:1.14.13"
kube-system    26m         Normal    Created                        Pod                       Created container
kube-system    26m         Normal    Started                        Pod                       Started container
kube-system    26m         Normal    Pulling                        Pod                       pulling image "k8s.gcr.io/prometheus-to-sd:v0.4.2"
kube-system    26m         Normal    Pulled                         Pod                       Successfully pulled image "k8s.gcr.io/prometheus-to-sd:v0.4.2"
kube-system    26m         Normal    Created                        Pod                       Created container
kube-system    26m         Normal    Started                        Pod                       Started container
kube-system    26m         Warning   FailedScheduling               Pod                       no nodes available to schedule pods
kube-system    26m         Normal    Scheduled                      Pod                       Successfully assigned kube-system/kube-dns-6987857fdb-xn4df to gke-knative-default-pool-0b861d45-pvmn
kube-system    26m         Warning   NetworkNotReady                Pod                       network is not ready: [runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: Kubenet does not have netConfig. This is most likely due to lack of PodCIDR]
kube-system    26m         Warning   FailedCreatePodSandBox         Pod                       Failed create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "9f2b6c688b9d1aa42ffe1c1c02b61713d683a2f66bc2be5fc93d08f7477fcede" network for pod "kube-dns-6987857fdb-xn4df": NetworkPlugin kubenet failed to set up pod "kube-dns-6987857fdb-xn4df_kube-system" network: Error adding container to network: failed to set bridge addr: could not add IP address to "cbr0": file exists
kube-system    26m         Normal    SandboxChanged                 Pod                       Pod sandbox changed, it will be killed and re-created.
kube-system    26m         Normal    Pulling                        Pod                       pulling image "k8s.gcr.io/k8s-dns-kube-dns-amd64:1.14.13"
kube-system    26m         Normal    Pulled                         Pod                       Successfully pulled image "k8s.gcr.io/k8s-dns-kube-dns-amd64:1.14.13"
kube-system    26m         Normal    Created                        Pod                       Created container
kube-system    26m         Normal    Started                        Pod                       Started container
kube-system    26m         Normal    Pulling                        Pod                       pulling image "k8s.gcr.io/k8s-dns-dnsmasq-nanny-amd64:1.14.13"
kube-system    26m         Normal    Pulled                         Pod                       Successfully pulled image "k8s.gcr.io/k8s-dns-dnsmasq-nanny-amd64:1.14.13"
kube-system    26m         Normal    Created                        Pod                       Created container
kube-system    26m         Normal    Started                        Pod                       Started container
kube-system    26m         Normal    Pulling                        Pod                       pulling image "k8s.gcr.io/k8s-dns-sidecar-amd64:1.14.13"
kube-system    26m         Normal    Pulled                         Pod                       Successfully pulled image "k8s.gcr.io/k8s-dns-sidecar-amd64:1.14.13"
kube-system    26m         Normal    Created                        Pod                       Created container
kube-system    26m         Normal    Started                        Pod                       Started container
kube-system    26m         Normal    Pulling                        Pod                       pulling image "k8s.gcr.io/prometheus-to-sd:v0.4.2"
kube-system    26m         Normal    Pulled                         Pod                       Successfully pulled image "k8s.gcr.io/prometheus-to-sd:v0.4.2"
kube-system    26m         Normal    Created                        Pod                       Created container
kube-system    26m         Normal    Started                        Pod                       Started container
kube-system    27m         Normal    SuccessfulCreate               ReplicaSet                Created pod: kube-dns-6987857fdb-xn4df
kube-system    26m         Normal    SuccessfulCreate               ReplicaSet                Created pod: kube-dns-6987857fdb-gpvkc
kube-system    26m         Normal    Scheduled                      Pod                       Successfully assigned kube-system/kube-dns-autoscaler-bb58c6784-mp2dm to gke-knative-default-pool-0b861d45-bs83
kube-system    26m         Normal    Pulled                         Pod                       Container image "k8s.gcr.io/cluster-proportional-autoscaler-amd64:1.3.0" already present on machine
kube-system    26m         Normal    Created                        Pod                       Created container
kube-system    26m         Normal    Started                        Pod                       Started container
kube-system    26m         Warning   FailedCreate                   ReplicaSet                Error creating: pods "kube-dns-autoscaler-bb58c6784-" is forbidden: error looking up service account kube-system/kube-dns-autoscaler: serviceaccount "kube-dns-autoscaler" not found
kube-system    26m         Normal    SuccessfulCreate               ReplicaSet                Created pod: kube-dns-autoscaler-bb58c6784-mp2dm
kube-system    27m         Normal    ScalingReplicaSet              Deployment                Scaled up replica set kube-dns-autoscaler-bb58c6784 to 1
kube-system    27m         Normal    ScalingReplicaSet              Deployment                Scaled up replica set kube-dns-6987857fdb to 1
kube-system    26m         Normal    ScalingReplicaSet              Deployment                Scaled up replica set kube-dns-6987857fdb to 2
kube-system    26m         Normal    Pulled                         Pod                       Container image "k8s.gcr.io/kube-proxy:v1.13.6-gke.5" already present on machine
kube-system    26m         Normal    Created                        Pod                       Created container
kube-system    26m         Normal    Started                        Pod                       Started container
kube-system    26m         Normal    Pulled                         Pod                       Container image "k8s.gcr.io/kube-proxy:v1.13.6-gke.5" already present on machine
kube-system    26m         Normal    Created                        Pod                       Created container
kube-system    26m         Normal    Started                        Pod                       Started container
kube-system    26m         Normal    Pulled                         Pod                       Container image "k8s.gcr.io/kube-proxy:v1.13.6-gke.5" already present on machine
kube-system    26m         Normal    Created                        Pod                       Created container
kube-system    26m         Normal    Started                        Pod                       Started container
kube-system    28m         Normal    LeaderElection                 Endpoints                 gke-f13d7152c1efe40b1782-b466-7a2c-vm_8573a1a0-8b27-11e9-9ba4-42010a8a0095 became leader
kube-system    27m         Normal    LeaderElection                 Endpoints                 gke-f13d7152c1efe40b1782-b466-7a2c-vm_a918feb3-8b27-11e9-a049-42010a8a0095 became leader
kube-system    26m         Warning   FailedScheduling               Pod                       no nodes available to schedule pods
kube-system    26m         Normal    Scheduled                      Pod                       Successfully assigned kube-system/l7-default-backend-fd59995cd-4cqw6 to gke-knative-default-pool-0b861d45-bs83
kube-system    26m         Warning   NetworkNotReady                Pod                       network is not ready: [runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: Kubenet does not have netConfig. This is most likely due to lack of PodCIDR]
kube-system    26m         Normal    Pulled                         Pod                       Container image "k8s.gcr.io/defaultbackend-amd64:1.5" already present on machine
kube-system    26m         Normal    Created                        Pod                       Created container
kube-system    26m         Normal    Started                        Pod                       Started container
kube-system    27m         Normal    SuccessfulCreate               ReplicaSet                Created pod: l7-default-backend-fd59995cd-4cqw6
kube-system    27m         Normal    ScalingReplicaSet              Deployment                Scaled up replica set l7-default-backend-fd59995cd to 1
kube-system    26m         Normal    Scheduled                      Pod                       Successfully assigned kube-system/metrics-server-v0.3.1-57c75779f-z2sp7 to gke-knative-default-pool-0b861d45-bs83
kube-system    26m         Normal    Pulled                         Pod                       Container image "k8s.gcr.io/metrics-server-amd64:v0.3.1" already present on machine
kube-system    26m         Normal    Created                        Pod                       Created container
kube-system    26m         Normal    Started                        Pod                       Started container
kube-system    26m         Normal    Pulled                         Pod                       Container image "k8s.gcr.io/addon-resizer:1.8.4" already present on machine
kube-system    26m         Normal    Created                        Pod                       Created container
kube-system    26m         Normal    Started                        Pod                       Started container
kube-system    26m         Normal    SuccessfulCreate               ReplicaSet                Created pod: metrics-server-v0.3.1-57c75779f-z2sp7
kube-system    26m         Warning   FailedScheduling               Pod                       no nodes available to schedule pods
kube-system    26m         Normal    Scheduled                      Pod                       Successfully assigned kube-system/metrics-server-v0.3.1-c4cddd5f5-2vp86 to gke-knative-default-pool-0b861d45-pvmn
kube-system    26m         Warning   NetworkNotReady                Pod                       network is not ready: [runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: Kubenet does not have netConfig. This is most likely due to lack of PodCIDR]
kube-system    26m         Normal    Pulled                         Pod                       Container image "k8s.gcr.io/metrics-server-amd64:v0.3.1" already present on machine
kube-system    26m         Normal    Created                        Pod                       Created container
kube-system    26m         Normal    Started                        Pod                       Started container
kube-system    26m         Normal    Pulled                         Pod                       Container image "k8s.gcr.io/addon-resizer:1.8.4" already present on machine
kube-system    26m         Normal    Created                        Pod                       Created container
kube-system    26m         Normal    Started                        Pod                       Started container
kube-system    24m         Warning   FailedMount                    Pod                       Unable to mount volumes for pod "metrics-server-v0.3.1-c4cddd5f5-2vp86_kube-system(bdcee164-8b27-11e9-b094-42010a8a0095)": timeout expired waiting for volumes to attach or mount for pod "kube-system"/"metrics-server-v0.3.1-c4cddd5f5-2vp86". list of unmounted volumes=[metrics-server-config-volume metrics-server-token-hgkqm]. list of unattached volumes=[metrics-server-config-volume metrics-server-token-hgkqm]
kube-system    26m         Normal    SuccessfulCreate               ReplicaSet                Created pod: metrics-server-v0.3.1-c4cddd5f5-2vp86
kube-system    26m         Normal    SuccessfulDelete               ReplicaSet                Deleted pod: metrics-server-v0.3.1-c4cddd5f5-2vp86
kube-system    26m         Normal    ScalingReplicaSet              Deployment                Scaled up replica set metrics-server-v0.3.1-c4cddd5f5 to 1
kube-system    26m         Normal    ScalingReplicaSet              Deployment                Scaled up replica set metrics-server-v0.3.1-57c75779f to 1
kube-system    26m         Normal    ScalingReplicaSet              Deployment                Scaled down replica set metrics-server-v0.3.1-c4cddd5f5 to 0
kube-system    26m         Warning   FailedScheduling               Pod                       0/2 nodes are available: 1 node(s) didn't match node selector, 1 node(s) had taints that the pod didn't tolerate.
kube-system    26m         Normal    Scheduled                      Pod                       Successfully assigned kube-system/prometheus-to-sd-b65l2 to gke-knative-default-pool-0b861d45-pvmn
kube-system    26m         Normal    Pulling                        Pod                       pulling image "k8s.gcr.io/prometheus-to-sd:v0.5.2"
kube-system    26m         Normal    Pulled                         Pod                       Successfully pulled image "k8s.gcr.io/prometheus-to-sd:v0.5.2"
kube-system    26m         Normal    Created                        Pod                       Created container
kube-system    26m         Normal    Started                        Pod                       Started container
kube-system    26m         Normal    Scheduled                      Pod                       Successfully assigned kube-system/prometheus-to-sd-qnpsm to gke-knative-default-pool-0b861d45-bb9t
kube-system    26m         Normal    Pulling                        Pod                       pulling image "k8s.gcr.io/prometheus-to-sd:v0.5.2"
kube-system    26m         Normal    Pulled                         Pod                       Successfully pulled image "k8s.gcr.io/prometheus-to-sd:v0.5.2"
kube-system    26m         Normal    Created                        Pod                       Created container
kube-system    26m         Normal    Started                        Pod                       Started container
kube-system    26m         Normal    Scheduled                      Pod                       Successfully assigned kube-system/prometheus-to-sd-z9sxg to gke-knative-default-pool-0b861d45-bs83
kube-system    26m         Normal    Pulling                        Pod                       pulling image "k8s.gcr.io/prometheus-to-sd:v0.5.2"
kube-system    26m         Normal    Pulled                         Pod                       Successfully pulled image "k8s.gcr.io/prometheus-to-sd:v0.5.2"
kube-system    26m         Normal    Created                        Pod                       Created container
kube-system    26m         Normal    Started                        Pod                       Started container
kube-system    26m         Normal    SuccessfulCreate               DaemonSet                 Created pod: prometheus-to-sd-b65l2
kube-system    26m         Normal    SuccessfulCreate               DaemonSet                 Created pod: prometheus-to-sd-z9sxg
kube-system    26m         Normal    SuccessfulCreate               DaemonSet                 Created pod: prometheus-to-sd-qnpsm
kube-system    26m         Warning   FailedScheduling               Pod                       no nodes available to schedule pods
kube-system    26m         Normal    Scheduled                      Pod                       Successfully assigned kube-system/stackdriver-metadata-agent-cluster-level-7b549bd965-8w4vp to gke-knative-default-pool-0b861d45-bs83
kube-system    26m         Warning   NetworkNotReady                Pod                       network is not ready: [runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: Kubenet does not have netConfig. This is most likely due to lack of PodCIDR]
kube-system    26m         Normal    Pulling                        Pod                       pulling image "gcr.io/stackdriver-agents/metadata-agent-go:1.0.2"
kube-system    26m         Normal    Pulled                         Pod                       Successfully pulled image "gcr.io/stackdriver-agents/metadata-agent-go:1.0.2"
kube-system    25m         Normal    Created                        Pod                       Created container
kube-system    25m         Normal    Started                        Pod                       Started container
kube-system    25m         Normal    Pulled                         Pod                       Container image "gcr.io/stackdriver-agents/metadata-agent-go:1.0.2" already present on machine
kube-system    25m         Warning   BackOff                        Pod                       Back-off restarting failed container
kube-system    27m         Normal    SuccessfulCreate               ReplicaSet                Created pod: stackdriver-metadata-agent-cluster-level-7b549bd965-8w4vp
kube-system    27m         Normal    ScalingReplicaSet              Deployment                Scaled up replica set stackdriver-metadata-agent-cluster-level-7b549bd965 to 1
***************************************
***         E2E TEST FAILED         ***
***     End of information dump     ***
***************************************
```

</details>

### PR DESCRIPTION
**Pull request by rhuss**
Fixes #174.

### CODE REVIEW

File: test/e2e-tests.sh [hunk 1]
```diff
@@ -31,7 +31,7 @@ source $(dirname $0)/../vendor/github.com/knative/test-infra/scripts/e2e-tests.s
 # Build kn before integration tests, so we fail fast in case of error.
 function cluster_setup() {
   header "Building client"
-  go build -v -mod=vendor ./cmd/... || return 1
+  $(dirname $0)/../hack/build.sh -u || return 1
```
Comment (houshengbo) [inline test/e2e-tests.sh]: I have got build github.com/knative/client/cmd/kn: cannot load k8s.io/api/admissionregistration/v1alpha1 locally with change. Do you know how to fix it? @rhuss

Comment (houshengbo) [reply test/e2e-tests.sh]: OK. I have resolved it. However, do you know it would be more straightforward to add
export GO111MODULE=on above Line 34, since $(dirname $0)/../hack/build.sh -u would go through 🕸️  Update 🚧 Compile 🧪  Test 🧹  Format and 📖 Docs. What we only need here is the compile.

Comment (houshengbo) [inline test/e2e-tests.sh]: @rhuss Do you think it is more straightforward to add export GO111MODULE=on above Line 34?
The command $(dirname $0)/../hack/build.sh -u goes thru 🕸️  Update 🚧 Compile
🧪  Test🧹  Format 📖 Docs, but we only need compile here.

Comment (adrcunha) [inline test/e2e-tests.sh]:
```suggestion
  ${REPO_ROOT_DIR}/hack/build.sh -u || return 1
```

Comment (rhuss) [reply test/e2e-tests.sh]: We can change to `build.sh -f` which just compiles.
