### PR TITLE
Server errors should not be tainted by client error messages

### LINKED ISSUE #1342: kn is presenting API server errors incorrectly
image (5)
image (4)

export WORKLOAD_NS=serverless-demo
kubectl create ns ${WORKLOAD_NS}

then When i run this - kn service create helloworld-go -n ${WORKLOAD_NS} \
  --image gcr.io/knative-samples/helloworld-go --env TARGET="from Serverless"

Error: Internal error occurred: failed calling webhook "webhook.serving.knative.dev": Post https://webhook.knative-serving.svc:443/defaulting?timeout=10s: context deadline exceeded

### PR DESCRIPTION
**Pull request by vyasgun**
## Description
In some cases, if an error  is from server but contains a substring that matches a client side error condition, the error returned by the server is being accompanied by the client side error message. This should not be the case.

## Changes

* Moved the server error parsing case up so it gets processed before we breakdown the error string for client level message.
* Added test cases.

## Reference

Fixes #1342

### CODE REVIEW

File: pkg/errors/factory.go [hunk 1]
```diff
@@ -47,16 +47,11 @@ func GetError(err error) error {
...
 	case isEmptyConfigError(err):
 		return newNoKubeConfig(err.Error())
-	case isNoRouteToHostError(err):
-		return newNoRouteToHost(err.Error())
-	default:
-		var errAPIStatus api_errors.APIStatus
-		if !errors.As(err, &errAPIStatus) {
-			return err
-		}
+	case errors.As(err, &errAPIStatus):
```
Comment (dsimansk) [inline pkg/errors/factory.go:54]: I'd suggest to add 2 new functions `isStatusError()` and then `newStatusError()` to wrap the handling of that case into it. I think it'd make the cases more self-explanatory.

File: pkg/errors/factory_test.go [hunk 2]
```diff
@@ -154,14 +165,49 @@ func TestIsForbiddenError(t *testing.T) {
...
 	assert.NilError(t, GetError(nil), nil)
 }
+
+func TestIsInternalError(t *testing.T) {
+	cases := []struct {
+		Name     string
+		Error    error
+		Internal bool
+	}{
+		{
```
Comment (dsimansk) [inline pkg/errors/factory_test.go:185]: Let's add `api_errors.NewTimeoutError` just to be sure.

Comment (dsimansk) [reply pkg/errors/factory_test.go:185]: It can be a separate test function or maybe a mix of different `StatusError` kinds.

**Review by dsimansk — CHANGES_REQUESTED** [review]
Please add a changelog entry. Sorry I haven't noticed sooner. :)

**Comment by vyasgun** [comment]
@dsimansk sorry I keep forgetting about adding the entry 😆

**Comment by dsimansk** [comment]
> @dsimansk sorry I keep forgetting about adding the entry laughing

Well, it happens to me all the time. :)

**Comment by dsimansk** [comment]
Thanks looks good to me. I'll leave open for a while for other to take a look.

/approve

File: pkg/errors/factory.go [hunk 3]
```diff
@@ -50,22 +71,11 @@ func GetError(err error) error {
 	switch {
 	case isEmptyConfigError(err):
 		return newNoKubeConfig(err.Error())
+	case isStatusError(err):
```
Comment (maximilien) [inline pkg/errors/factory.go:74]: Should this be moved up and considered first?

File: pkg/errors/factory_test.go [hunk 4]
```diff
@@ -154,14 +167,82 @@ func TestIsForbiddenError(t *testing.T) {
...
+			Name:     "internal error with i/o timeout",
+			Error:    api_errors.NewInternalError(fmt.Errorf("failed calling webhook \"webhook.serving.knative.dev\": Post https://webhook.knative-serving.svc:443/defaulting?timeout=10s: i/o timeout")),
+			Internal: true,
+		},
+		{
+			Name:     "not internal error",
+			Error:    mockErrType{},
+			Internal: false,
+		},
```
Comment (maximilien) [inline pkg/errors/factory_test.go:206]: What about unknown errors? Or the previous covers it?

**Review by maximilien — COMMENTED** [review]
Left a few comments and questions. Thanks for the contribution.

File: pkg/errors/factory.go (hunk 3 above)
Comment (dsimansk) [reply pkg/errors/factory.go:74]: +1
I'd say that `no configuration has been provided` message is quiet distinctive from k8s api erros, but it's good idea to have it at first place to check.

File: pkg/errors/factory_test.go (hunk 4 above)
Comment (vyasgun) [reply pkg/errors/factory_test.go:206]: The previous function covers the non k8s api errors. This one covers a mock one which implements the k8s api interface.

Comment (dsimansk) [reply pkg/errors/factory_test.go:206]: @maximilien any more comments to the above please?

**Comment by dsimansk** [comment]
As I don't see any new comments, I'd say it's done. :)

Thanks @vyasgun!
/approve
/lgtm
