### PR TITLE
fix(e2e): Improves the error message upon mismatch of traffic targets

### LINKED ISSUE #434: Integration Test Flake
## In what area(s)?
E2E Testing

In this [E2E Test run](https://prow.knative.dev/view/gcs/knative-prow/pr-logs/pull/knative_client/432/pull-knative-client-integration-tests/1181485419032743939) an error occurred which is unrelated to the change in the PR:

```
--- PASS: TestServiceOptions/create,_update_and_validate_service_with_annotations (12.40s)
--- FAIL: TestTrafficSplit (364.94s)
    --- PASS: TestTrafficSplit/tag_two_revisions_as_v1_and_v2_and_give_50-50%_share (39.85s)
    --- FAIL: TestTrafficSplit/ramp/up_down_a_revision_to_20%_adjusting_other_traffic_to_accommodate (18.39s)
        traffic_split_test.go:367: assertion failed: error is not nil: expecting to receive parts of length 2, got 1 string: ,echo1-qkwgb-3,100,true seprator: |
    --- PASS: TestTrafficSplit/tag_a_revision_as_candidate,_without_otherwise_changing_any_traffic_split (12.07s)
    --- PASS: TestTrafficSplit/tag_a_revision_as_candidate,_set_2%_traffic_adjusting_other_traffic_to_accommodate (13.04s) 
```

### PR DESCRIPTION
**Pull request by navidshaikh**
Fixes #434
/lint

## Proposed Changes
 - The error message now prints the expected/actual length of traffic targets
 - Also prints the actual traffic targets

### CODE REVIEW

File: test/e2e/traffic_split_test.go [hunk 1]
```diff
@@ -51,10 +50,11 @@ func newTargetFields(tag, revision string, percent int, latest bool) TargetField
...
 
 func splitTargets(s, separator string, partsCount int) ([]string, error) {
-	parts := strings.SplitN(s, separator, partsCount)
+	s = strings.TrimSuffix(s, targetsSeparator)
+	parts := strings.Split(s, separator)
 	if len(parts) != partsCount {
-		return nil, errors.New(fmt.Sprintf("expecting to receive parts of length %d, got %d "+
-			"string: %s seprator: %s", partsCount, len(parts), s, separator))
+		return nil, fmt.Errorf("expecting %d targets, got %d targets "+
+			"targets: %s seprator: %s", partsCount, len(parts), s, separator)
```
Comment (rhuss) [inline test/e2e/traffic_split_test.go]:
```suggestion
			"targets: %s seperator: %s", partsCount, len(parts), s, separator)
```
