### PR TITLE
Remove Use of os.Exit() and Return Error Instead

### LINKED ISSUE #850: Avoid `os.Exit(...)` calls other than in top level command handling in `main.go`
### Bug report

This is not technically a bug but rather a "code smell". Came from [discussions](https://github.com/knative/client/pull/834#discussion_r427206020) in PR #834 with @rhuss 

### Expected behavior

No change except we should not be exiting using `os.Exit(...)` anywhere but top level calls ideally in `main.go`

### Steps to reproduce the problem

N/A

### kn version

```
➜  client git:(issue827) ./kn version
Version:      v20200521-local-9803cd6e
Build Date:   2020-05-21 22:17:42
Git Revision: 9803cd6e
Supported APIs:
* Serving
  - serving.knative.dev/v1 (knative-serving v0.14.0)
* Eventing
  - sources.knative.dev/v1alpha2 (knative-eventing v0.14.1)
  - eventing.knative.dev/v1alpha1 (knative-eventing v0.14.1)
```

### Knative (serving/eventing) version

> 0.14.x

> /kind good-first-issue
> /kind cleanup

### PR DESCRIPTION
**Pull request by danielhelfand**
## Description

This pull request removes the use of `os.Exit(1)` from areas of `kn` with the exception of `main.go` and `generate-docs.go`. Instead of using `os.Exit(1)` an error is returned now and handled in `main.go`.

Can also work of removing from `generate-docs.go`, but my thought was the issue was meant to address this in `kn`.

Can wait for #834 and rebase if that is preferred.

## Reference

Fixes #850 

/lint

### CODE REVIEW

File: test/e2e/basic_workflow_test.go [hunk 1]
```diff
@@ -82,7 +82,7 @@ func TestWrongCommand(t *testing.T) {
 	r.AssertError(out)
 
 	out = test.Kn{}.Run("rev")
-	assert.Check(t, util.ContainsAll(out.Stderr, "Error", "unknown command", "rev"))
+	assert.Check(t, util.ContainsAll(out.Stderr, "unknown command", "rev"))
```
Comment (danielhelfand) [inline test/e2e/basic_workflow_test.go:85]: Something to make note of here. `Error` no longer is part of the error message for unknown command.
