### PR TITLE
Fix shellcheck warnings in hack/build.sh script

### LINKED ISSUE #1859: Fix shellcheck warnings in hack/build.sh script
There are a few warnings in our `./hack/build.sh` script that would be nice to fix. It might pop-up in case of changing the script in the future.

There are several more with `INFO` severity level. Those can be ignored for now. 

```
➜  client git:(main) shellcheck -S warning hack/build.sh

In hack/build.sh line 40:
  pushd $(basedir) >/dev/null 2>&1
        ^--------^ SC2046 (warning): Quote this to prevent word splitting.


In hack/build.sh line 43:
  if $(has_flag --help -h); then
     ^-------------------^ SC2091 (warning): Remove surrounding $() to avoid executing output (or use eval if intentional).


In hack/build.sh line 48:
  if $(has_flag --watch -w); then
     ^--------------------^ SC2091 (warning): Remove surrounding $() to avoid executing output (or use eval if intentional).


In hack/build.sh line 52:
    if $(has_flag --test -t); then
       ^-------------------^ SC2091 (warning): Remove surrounding $() to avoid executing output (or use eval if intentional).


In hack/build.sh line 61:
  if $(has_flag --fast -f); then
     ^-------------------^ SC2091 (warning): Remove surrounding $() to avoid executing output (or use eval if intentional).


In hack/build.sh line 64:
    if $(has_flag --test -t); then
       ^-------------------^ SC2091 (warning): Remove surrounding $() to avoid executing output (or use eval if intentional).


In hack/build.sh line 71:
  if $(has_flag --test -t); then
     ^-------------------^ SC2091 (warning): Remove surrounding $() to avoid executing output (or use eval if intentional).


In hack/build.sh line 77:
  if $(has_flag --codegen -c); then
     ^----------------------^ SC2091 (warning): Remove surrounding $() to avoid executing output (or use eval if intentional).


In hack/build.sh line 83:
  if $(has_flag --all -x); then
     ^------------------^ SC2091 (warning): Remove surrounding $() to avoid executing output (or use eval if intentional).


In hack/build.sh line 118:
  find $(echo "$source_dirs") -name "*.go" -print0 | xargs -0 gofmt -s -w
       ^--------------------^ SC2046 (warning): Quote this to prevent word splitting.


In hack/build.sh line 123:
  go_run "golang.org/x/tools/cmd/goimports@${GOIMPORTS_VERSION}" -w $(echo "$source_dirs")
                                                                    ^--------------------^ SC2046 (warning): Quote this to prevent word splitting.


In hack/build.sh line 124:
  find $(echo "$source_dirs") -name "*.go" -print0 | xargs -0 gofmt -s -w
       ^--------------------^ SC2046 (warning): Quote this to prevent word splitting.


In hack/build.sh line 139:
  if $(file kn | grep -q -i "Windows"); then
     ^-- SC2091 (warning): Remove surrounding $() to avoid executing output (or use eval if intentional).


In hack/build.sh line 199:
  $(basedir)/hack/update-deps.sh
  ^--------^ SC2046 (warning): Quote this to prevent word splitting.


In hack/build.sh line 211:
    local fswatch_opts='-e "^\..*$" -o pkg cmd'
                       ^----------------------^ SC2089 (warning): Quotes/backslashes will be treated literally. Use an array.


In hack/build.sh line 212:
    if $(has_flag --test -t); then
       ^-------------------^ SC2091 (warning): Remove surrounding $() to avoid executing output (or use eval if intentional).


In hack/build.sh line 215:
    if $(has_flag --verbose); then
       ^-------------------^ SC2091 (warning): Remove surrounding $() to avoid executing output (or use eval if intentional).


In hack/build.sh line 231:
    fswatch $fswatch_opts | xargs -n1 -I{} sh -c "$command && echo 👌 OK"
            ^-----------^ SC2090 (warning): Quotes/backslashes in this variable will not be respected.


In hack/build.sh line 261:
    filters="$@"
            ^--^ SC2124 (warning): Assigning an array to a string! Assign as array, or use * instead of @ to concatenate.


In hack/build.sh line 321:
display_help() {
^-- SC2120 (warning): display_help references arguments, but none are ever passed.


In hack/build.sh line 326:
Usage: $(basename $BASH_SOURCE) [... options ...]
                  ^----------^ SC2128 (warning): Expanding an array without an index only gives the first element.


In hack/build.sh line 356:
if $(has_flag --debug); then
   ^-----------------^ SC2091 (warning): Remove surrounding $() to avoid executing output (or use eval if intentional).


In hack/build.sh line 362:
source $(basedir)/vendor/knative.dev/hack/library.sh
       ^--------^ SC2046 (warning): Quote this to prevent word splitting.


In hack/build.sh line 366:
  source "${file}"
         ^-------^ SC1090 (warning): ShellCheck can't follow non-constant source. Use a directive to specify location.


In hack/build.sh line 368:
source $(basedir)/hack/build-flags.sh
       ^--------^ SC2046 (warning): Quote this to prevent word splitting.

For more information:
  https://www.shellcheck.net/wiki/SC1090 -- ShellCheck can't follow non-const...
  https://www.shellcheck.net/wiki/SC2046 -- Quote this to prevent word splitt...
  https://www.shellcheck.net/wiki/SC2089 -- Quotes/backslashes will be treate...
```

/kind cleanup
/kind good-first-issue

### PR DESCRIPTION
**Pull request by xiangpingjiang**
## Changes

* build.sh script

## Reference

Fixes #1859 

**Release Note**

```release-note
Fix shellcheck warnings in `hack/build.sh` script
```

### CODE REVIEW

File: hack/build.sh [hunk 1]
```diff
@@ -58,29 +60,29 @@ run() {
   fi
 
   # Fast mode: Only compile and maybe run test
-  if $(has_flag --fast -f); then
+  if has_flag --fast -f; then
```
Comment (rhuss) [inline hack/build.sh:63]: This is not as it is supposed to work: `has_flag` _echos_ `true` or `false` and this should be evaluated as a command. So running it in a subshell is the right way todo this construct. The warnings from the linter are bogus. As it is now, it won't work as `if` would evaluate the return code, which is always 0 (so all flags are set). I would recommend to keep as is or change `has_flag` to have a different semantics (but then, why ?).

Comment (dsimansk) [reply hack/build.sh:63]: Shellcheck would be happy with `if eval "$(has_flag --fast -f)"`. Ref: https://www.shellcheck.net/wiki/SC2091

It's a bit tricky in this case with `has_flag` design. But I'd opt for adding eval rather than rewriting the function. IMO it's beyond my initial intention to get rid off `shellcheck` warnings.

Indeed the `has_flag` parts are failing current integration tests execution, because of the flags must be evaluated bug @rhuss described above.

File: hack/build.sh [hunk 2]
```diff
@@ -37,19 +39,19 @@ run() {
   export GO111MODULE=on
 
   # Jump into project directory
-  pushd $(basedir) >/dev/null 2>&1
+  pushd "$(basedir)" >/dev/null 2>&1
 
   # Print help if requested
-  if $(has_flag --help -h); then
+  if eval "$(has_flag --help -h)"; then
```
Comment (dsimansk) [inline hack/build.sh:45]: @rhuss are you OK with the proposed to solution to fix shellcheck's warning?

File: hack/build.sh (hunk 1 above)
Comment (rhuss) [reply hack/build.sh]: tbh, I would prefer then to adapt `has_flag` to return 0 or 1 and then keep that `$(has_flag ...)` syntax (instead of adding the eval). The whole purpose of the original form was that is was just shorter. Adding an `eval` would counteract this.

File: hack/build.sh (hunk 2 above)
Comment (rhuss) [reply hack/build.sh:45]: see my comment above, I would prefer to adapt `$has_flag` to return a 0 or 1 (instead of `true` or `false` that then is interpreted as a UNIX command)

Comment (dsimansk) [reply hack/build.sh:45]: @rhuss sure, thanks!

Comment (dsimansk) [reply hack/build.sh:45]: @xiangpingjiang sorry for misleading you with my previous comment. If you don't mind to rework it again a bit within Roland's direction.

File: hack/build.sh (hunk 1 above)
Comment (xiangpingjiang) [reply hack/build.sh]: @rhuss 
If we adapt has_flag return 0 or 1 like below 

```bash
has_flag() {
    filters="$*"
    for var in "${ARGS[@]}"; do
        for filter in $filters; do
          if [ "$var" = "$filter" ]; then
              return 0
          fi
        done
    done
    return 1
}
```

this will work
```bash
if has_flag --help -h; then
    display_help
    exit 0
fi
```


Do we still need keep that $(has_flag ...) syntax ?

Comment (rhuss) [reply hack/build.sh]: nope, it's perfectly fine to change completely to your proposal. Thanks!

File: hack/build.sh [hunk 3]
```diff
@@ -258,16 +260,15 @@ basedir() {
 
 # Checks if a flag is present in the arguments.
 has_flag() {
-    filters="$@"
+    filters="$*"
```
Comment (rhuss) [inline hack/build.sh:263]: I would like to keep "$@" as this will honour quotes for flags, two (e.g. `--flag "my input"`). I'm not sure why shellchecks recommends $* here.

File: hack/build.sh [hunk 4]
```diff
@@ -323,7 +324,7 @@ display_help() {
     cat <<EOT
 Knative client build script
 
-Usage: $(basename $BASH_SOURCE) [... options ...]
+Usage: $(basename "${BASH_SOURCE[@]}") [... options ...]
```
Comment (rhuss) [inline hack/build.sh:327]: I don't think that makes much sense, as this script is never meant to be sourced  by another script (which only then makes a difference to the original version)

Comment (rhuss) [reply hack/build.sh:327]: So I would keep the original version or use "${BASH_SOURCE[0]}" if this makes shellcheck happier

File: hack/build.sh [hunk 5]
```diff
@@ -352,20 +353,21 @@ Examples:
 * Build cross platform binaries: ..... build.sh --all
 EOT
 }
+display_help "$@"
```
Comment (rhuss) [inline hack/build.sh:356]: why should the help message always be displayed ? Maybe a debug left-over ?

**Comment by rhuss** [comment]
Some minor comments, otherwise looks good to me. Thanks @xiangpingjiang !

**Comment by xiangpingjiang** [comment]
> Some minor comments, otherwise looks good to me. Thanks @xiangpingjiang !
@rhuss , Thanks for your reviews, I corrected your comments, could you review  my latest  code ?

**Comment by rhuss** [comment]
Thanks! Looks good to me, thanks a lot for patience :-)

/approve
/lgtm
