### PR TITLE
fix: Fix service export annotations

### LINKED ISSUE #1002: [e2e][service export] Test failing with a couple of additional annotations in comparison
excerpts from https://prow.knative.dev/view/gs/knative-prow/pr-logs/pull/knative_client/1001/pull-knative-client-integration-tests/1303741255074713600#1:build-log.txt%3A834 (serving nightly)

```
   service_export_test.go:105: export service-revision2 after tagging kubernetes-resources
    service_export_test.go:321: assertion failed: 
        --- &expServiceList
        +++ &actSvcList
          &v1.ServiceList{
          	TypeMeta: {Kind: "List", APIVersion: "v1"},
          	ListMeta: {},
          	Items: []v1.Service{
          		{
          			TypeMeta:   {Kind: "Service", APIVersion: "serving.knative.dev/v1"},
          			ObjectMeta: {Name: "hello"},
          			Spec: v1.ServiceSpec{
          				ConfigurationSpec: v1.ConfigurationSpec{
          					Template: v1.RevisionTemplateSpec{
          						ObjectMeta: v1.ObjectMeta{
          							... // 9 identical fields
          							DeletionGracePeriodSeconds: nil,
          							Labels:                     nil,
          							Annotations: map[string]string{
          								"client.knative.dev/user-image":            "gcr.io/knative-boskos-88/kclient-e2e-img/25094/helloworld:latest",
        + 								"serving.knative.dev/routes":               "hello",
        + 								"serving.knative.dev/routingStateModified": "2020-09-09T17:16:08Z",
          							},
          							OwnerReferences: nil,
          							Finalizers:      nil,
[...]
```

### PR DESCRIPTION
**Pull request by dsimansk**
## Description

There are 2 new annotations and 1 label added to Service metadata that currently break our E2E export tests.

Annotations:
- serving.knative.dev/routes
- serving.knative.dev/routingStateModified.

Labels:
-  serving.knative.dev/routingState

## Changes

* Add `serving.knative.dev/routingStateModified` annotation to ignored export list
* Correct E2E expected values.

## Reference

Fixes #1002

### CODE REVIEW

**Comment by dsimansk** [comment]
Surprisingly, the fix is actually not passing, even though I've got all tests passed on local instance. Somehow on the CI there's exactly the opposite [result](https://prow.knative.dev/view/gs/knative-prow/pr-logs/pull/knative_client/1004/pull-knative-client-integration-tests-latest-release/1303776990574153728#1:build-log.txt%3A815).

**Comment by itsmurugappan** [comment]
> Surprisingly, the fix is actually not passing, even though I've got all tests passed on local instance. Somehow on the CI there's exactly the opposite

It passed with the knative serving nightly version, failed on the latest release (0.17), which is correct right .

**Comment by navidshaikh** [comment]
> It passed with the knative serving nightly version, failed on the latest release (0.17), which is correct right .

Yup, since the changes are in serving master but not in 0.17.

I think we can keep this updated test and skip running it and enable back in the 1 week release buffer between serving and client 0.18, wdyt ?

**Comment by itsmurugappan** [comment]
Agree. We can skip for a week.

**Comment by dsimansk** [comment]
Ahh, thanks for explanation. I mixed up the names and assumed `latest == nightly`, it makes sense now. :exploding_head: 

I've added generic skip, but maybe conditional would be better `$KNATIVE_SERVING_VERSION == "0.17.0"`?

File: test/e2e/service_export_test.go [hunk 1]
```diff
@@ -43,6 +45,10 @@ type expectedKNExportOption func(*clientv1alpha1.Export)
 type podSpecOption func(*corev1.PodSpec)
 
 func TestServiceExport(t *testing.T) {
+	//FIXME: enable once 0.18 is available
+	if strings.HasPrefix(os.Getenv("KNATIVE_SERVING_VERSION"), "0.17") {
+		t.Skip("The test is skipped on Serving version 0.17")
+	}
```
Comment (navidshaikh) [inline test/e2e/service_export_test.go:51]: :+1:

**Review by navidshaikh — APPROVED** [review]
/lgtm
/approve
